export const AI_AUDITOR_CARD_AUDIT_SCHEMA = {
  name: "oddsphere_card_auditor_v1",
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "data_integrity_review",
      "market_read_review",
      "play_grade_review",
      "betting_value_review",
      "full_card_coherence_review",
      "recommended_market_read",
      "recommended_play_grade",
      "market_reviews",
      "issues",
      "recommended_actions",
      "safe_copy_fixes",
      "repair_actions",
      "safety_review",
      "confidence",
      "severity",
      "provider_name_check",
    ],
    properties: {
      data_integrity_review: {
        type: "object",
        additionalProperties: false,
        required: ["status", "summary", "flags"],
        properties: {
          status: { type: "string", enum: ["pass", "warn", "block"] },
          summary: { type: "string" },
          flags: { type: "array", items: { type: "string" } },
        },
      },
      market_read_review: {
        type: "object",
        additionalProperties: false,
        required: ["status", "summary", "current_market_read", "recommended_market_read"],
        properties: {
          status: { type: "string", enum: ["pass", "warn", "block"] },
          summary: { type: "string" },
          current_market_read: { type: "string" },
          recommended_market_read: {
            type: "string",
            enum: ["aligned", "mixed", "resistance", "consensus_support", "consensus_resistance", "no_clear_signal", "insufficient_data"],
          },
        },
      },
      play_grade_review: {
        type: "object",
        additionalProperties: false,
        required: ["status", "summary", "current_play_grade", "recommended_play_grade"],
        properties: {
          status: { type: "string", enum: ["pass", "warn", "block"] },
          summary: { type: "string" },
          current_play_grade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
          recommended_play_grade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
        },
      },
      betting_value_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "status",
          "summary",
          "real_model_edge",
          "price_playable",
          "edge_large_enough_for_grade",
          "market_resistance_meaningful",
          "mixed_market_signal_is_noise",
          "risk_reward_good_enough_for_action",
          "recommended_grade_direction",
          "disciplined_bettor_action",
        ],
        properties: {
          status: { type: "string", enum: ["pass", "warn", "block"] },
          summary: { type: "string" },
          real_model_edge: { type: "boolean" },
          price_playable: { type: "boolean" },
          edge_large_enough_for_grade: { type: "boolean" },
          market_resistance_meaningful: { type: "boolean" },
          mixed_market_signal_is_noise: { type: "boolean" },
          risk_reward_good_enough_for_action: { type: "boolean" },
          recommended_grade_direction: { type: "string", enum: ["downgrade", "promote", "hold", "copy_only", "data_repair"] },
          disciplined_bettor_action: { type: "string", enum: ["pass", "watch", "lean", "play"] },
        },
      },
      full_card_coherence_review: {
        type: "object",
        additionalProperties: false,
        required: ["status", "summary", "contradictions"],
        properties: {
          status: { type: "string", enum: ["pass", "warn", "block"] },
          summary: { type: "string" },
          contradictions: { type: "array", items: { type: "string" } },
        },
      },
      recommended_market_read: {
        type: "string",
        enum: ["aligned", "mixed", "resistance", "consensus_support", "consensus_resistance", "no_clear_signal", "insufficient_data"],
      },
      recommended_play_grade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
      market_reviews: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "market",
            "current_market_read",
            "recommended_market_read",
            "current_play_grade",
            "recommended_play_grade",
            "data_integrity_status",
            "source_conflict",
            "summary",
          ],
          properties: {
            market: { type: "string", enum: ["moneyline", "total", "first_inning"] },
            current_market_read: { type: "string" },
            recommended_market_read: {
              type: "string",
              enum: ["aligned", "mixed", "resistance", "consensus_support", "consensus_resistance", "no_clear_signal", "insufficient_data"],
            },
            current_play_grade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
            recommended_play_grade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
            data_integrity_status: {
              type: "string",
              enum: ["ok", "critical_data_issue", "non_critical_data_warning", "historical_replay_limitation", "optional_source_unavailable", "missing", "stale", "partial", "reversed", "inconsistent", "historical_source_not_persisted"],
            },
            source_conflict: { type: "boolean" },
            summary: { type: "string" },
          },
        },
      },
      issues: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["code", "severity", "materiality_to_bet", "should_affect_grade", "direction", "message"],
          properties: {
            code: { type: "string" },
            severity: { type: "string", enum: ["info", "low", "medium", "high", "block"] },
            materiality_to_bet: { type: "string", enum: ["low", "medium", "high"] },
            should_affect_grade: { type: "boolean" },
            direction: { type: "string", enum: ["downgrade", "promote", "hold", "copy_only", "data_repair"] },
            message: { type: "string" },
          },
        },
      },
      recommended_actions: {
        type: "array",
        items: {
          type: "string",
          enum: ["none", "apply_copy_fixes", "downgrade_grade", "block_card", "repair_data", "escalate_to_mini"],
        },
      },
      safe_copy_fixes: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["field", "replacement"],
          properties: {
            field: { type: "string" },
            replacement: { type: "string" },
          },
        },
      },
      repair_actions: {
        type: "array",
        items: {
          type: "string",
          enum: ["none", "rerun_fetch", "mark_source_unavailable", "block_card", "repair_mapping", "refresh_lineup_or_starter", "refresh_splits", "review_price"],
        },
      },
      safety_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "postgame_data_present",
          "provider_names_present",
          "invented_data_detected",
          "invalid_grade_label",
          "attempted_pick_flip",
          "attempted_probability_change",
          "attempted_projected_score_change",
          "attempted_best_angle_upgrade",
        ],
        properties: {
          postgame_data_present: { type: "boolean" },
          provider_names_present: { type: "boolean" },
          invented_data_detected: { type: "boolean" },
          invalid_grade_label: { type: "boolean" },
          attempted_pick_flip: { type: "boolean" },
          attempted_probability_change: { type: "boolean" },
          attempted_projected_score_change: { type: "boolean" },
          attempted_best_angle_upgrade: { type: "boolean" },
        },
      },
      confidence: { type: "number", minimum: 0, maximum: 1 },
      severity: { type: "string", enum: ["info", "low", "medium", "high", "block"] },
      provider_name_check: {
        type: "object",
        additionalProperties: false,
        required: ["provider_names_present", "offending_terms"],
        properties: {
          provider_names_present: { type: "boolean" },
          offending_terms: { type: "array", items: { type: "string" } },
        },
      },
    },
  },
  strict: true,
} as const;
