import type { PredictionEvidenceObject } from "@/lib/services/dailyEdge/predictionEvidenceBuilder";

export const AI_DAILY_EDGE_INTELLIGENCE_REVIEW_VARIANT = "ai_v5_daily_edge_intelligence_review" as const;

export type AiDailyEdgeIntelligenceVariant = typeof AI_DAILY_EDGE_INTELLIGENCE_REVIEW_VARIANT;

export const AI_DAILY_EDGE_INTELLIGENCE_REVIEW_SCHEMA = {
  name: "oddsphere_daily_edge_intelligence_review_v1",
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "model_stats_review",
      "market_read_review",
      "price_value_review",
      "grade_alignment_review",
      "reader_coherence_review",
      "slate_balance_flags",
      "safety_review",
      "confidence",
      "severity",
    ],
    properties: {
      model_stats_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "modelStatVerdict",
          "modelInputStrengthScore",
          "projectionQualityScore",
          "statSupportReasons",
          "modelConcernReasons",
          "projectionConcernReasons",
          "inputDataQualityVerdict",
          "modelStatSummary",
        ],
        properties: {
          modelStatVerdict: { type: "string", enum: ["strong", "moderate", "weak", "insufficient"] },
          modelInputStrengthScore: { type: "number", minimum: 0, maximum: 100 },
          projectionQualityScore: { type: "number", minimum: 0, maximum: 100 },
          statSupportReasons: { type: "array", items: { type: "string" } },
          modelConcernReasons: { type: "array", items: { type: "string" } },
          projectionConcernReasons: { type: "array", items: { type: "string" } },
          inputDataQualityVerdict: { type: "string" },
          modelStatSummary: { type: "string" },
        },
      },
      market_read_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "marketReadLabel",
          "marketSupportScore",
          "marketResistanceScore",
          "consensusInterpretation",
          "sharpBookInterpretation",
          "lineMovementInterpretation",
          "sourceAgreementLabel",
          "marketReadMateriality",
          "marketReadSummary",
          "memberFacingMarketReadCopy",
        ],
        properties: {
          marketReadLabel: {
            type: "string",
            enum: [
              "clean_market_support",
              "consensus_support",
              "sharp_book_support",
              "mixed_but_playable",
              "market_resistance",
              "market_resistance_with_model_value_override",
              "price_capped",
              "no_clear_market_signal",
              "insufficient_core_data",
              "fi_model_support",
              "fi_price_support",
              "fi_line_movement_support",
              "fi_mixed",
              "fi_data_caution",
              "fi_insufficient_core_data",
            ],
          },
          marketSupportScore: { type: "number", minimum: 0, maximum: 100 },
          marketResistanceScore: { type: "number", minimum: 0, maximum: 100 },
          consensusInterpretation: { type: "string" },
          sharpBookInterpretation: { type: "string" },
          lineMovementInterpretation: { type: "string" },
          sourceAgreementLabel: { type: "string" },
          marketReadMateriality: { type: "string", enum: ["low", "medium", "high"] },
          marketReadSummary: { type: "string" },
          memberFacingMarketReadCopy: { type: "string" },
        },
      },
      price_value_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "priceQualityScore",
          "edgeQualityScore",
          "bettingValueVerdict",
          "priceConcernReasons",
          "edgeConcernReasons",
          "valueSummary",
        ],
        properties: {
          priceQualityScore: { type: "number", minimum: 0, maximum: 100 },
          edgeQualityScore: { type: "number", minimum: 0, maximum: 100 },
          bettingValueVerdict: {
            type: "string",
            enum: ["strong_value", "playable_value", "thin_value", "bad_price", "no_value", "insufficient"],
          },
          priceConcernReasons: { type: "array", items: { type: "string" } },
          edgeConcernReasons: { type: "array", items: { type: "string" } },
          valueSummary: { type: "string" },
        },
      },
      grade_alignment_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "originalPlayGrade",
          "gradeAlignmentVerdict",
          "suggestedPlayGrade",
          "maxReasonableGrade",
          "actionVsOriginal",
          "winCaseStrengthScore",
          "bettingValueStrengthScore",
          "marketContextScore",
          "readQualityScore",
          "riskPenaltyScore",
          "priceQualityScore",
          "modelStatSupportScore",
          "dataQualityScore",
          "bestAngleProfile",
          "gradeReasonType",
          "bestAngleThesis",
          "whyMarketFrictionDoesOrDoesNotBlock",
          "whyPriceDoesOrDoesNotBlock",
          "whyThisCanOrCannotBeTopTier",
          "evidenceForUpgrade",
          "evidenceForDowngrade",
          "materialBlockers",
          "publicActionability",
          "gradeReason",
          "gradeChangeRecommended",
          "gradeChangeDirection",
          "gradeChangeMateriality",
          "gradeChangeEvidence",
          "primaryGradeChangeReason",
          "whyCopyOnlyIsNotEnough",
          "isRiskCopyEnough",
          "marketReadImprovementRecommended",
          "supportingEvidenceImprovementRecommended",
          "riskNoteImprovementRecommended",
          "copyOnlyImprovementRecommended",
          "humanReviewRecommended",
          "overgradedCandidate",
          "undergradedCandidate",
          "overgradeReason",
          "undergradeReason",
          "upgradeEvidence",
          "downgradeEvidence",
        ],
        properties: {
          originalPlayGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
          gradeAlignmentVerdict: {
            type: "string",
            enum: [
              "aligned",
              "possibly_overgraded",
              "strongly_overgraded",
              "possibly_undergraded",
              "strongly_undergraded",
            ],
          },
          suggestedPlayGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
          maxReasonableGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
          actionVsOriginal: { type: "string", enum: ["hold", "promote", "downgrade"] },
          winCaseStrengthScore: { type: "number", minimum: 0, maximum: 100 },
          bettingValueStrengthScore: { type: "number", minimum: 0, maximum: 100 },
          marketContextScore: { type: "number", minimum: 0, maximum: 100 },
          readQualityScore: { type: "number", minimum: 0, maximum: 100 },
          riskPenaltyScore: { type: "number", minimum: 0, maximum: 100 },
          priceQualityScore: { type: "number", minimum: 0, maximum: 100 },
          modelStatSupportScore: { type: "number", minimum: 0, maximum: 100 },
          dataQualityScore: { type: "number", minimum: 0, maximum: 100 },
          bestAngleProfile: {
            type: "string",
            enum: [
              "clean_alignment",
              "model_edge_value",
              "plus_money_value",
              "sharp_market_confirmation",
              "strong_win_case_playable_price",
              "none",
            ],
          },
          gradeReasonType: {
            type: "string",
            enum: [
              "clean_alignment",
              "model_value_edge",
              "strong_win_case",
              "plus_money_value",
              "sharp_market_confirmation",
              "market_mixed_but_playable",
              "price_capped",
              "market_resistance_capped",
              "thin_edge_watchlist",
              "data_quality_caution",
              "bad_price_no_play",
              "insufficient_core_evidence",
              "fi_toss_up_no_play",
            ],
          },
          bestAngleThesis: { type: "string" },
          whyMarketFrictionDoesOrDoesNotBlock: { type: "string" },
          whyPriceDoesOrDoesNotBlock: { type: "string" },
          whyThisCanOrCannotBeTopTier: { type: "string" },
          evidenceForUpgrade: { type: "array", items: { type: "string" } },
          evidenceForDowngrade: { type: "array", items: { type: "string" } },
          materialBlockers: { type: "array", items: { type: "string" } },
          publicActionability: { type: "boolean" },
          gradeReason: { type: "string" },
          gradeChangeRecommended: { type: "boolean" },
          gradeChangeDirection: { type: "string", enum: ["promote", "downgrade", "hold"] },
          gradeChangeMateriality: { type: "string", enum: ["low", "medium", "high"] },
          gradeChangeEvidence: { type: "array", items: { type: "string" } },
          primaryGradeChangeReason: { type: "string" },
          whyCopyOnlyIsNotEnough: { type: "string" },
          isRiskCopyEnough: { type: "boolean" },
          marketReadImprovementRecommended: { type: "boolean" },
          supportingEvidenceImprovementRecommended: { type: "boolean" },
          riskNoteImprovementRecommended: { type: "boolean" },
          copyOnlyImprovementRecommended: { type: "boolean" },
          humanReviewRecommended: { type: "boolean" },
          overgradedCandidate: { type: "boolean" },
          undergradedCandidate: { type: "boolean" },
          overgradeReason: { type: "string" },
          undergradeReason: { type: "string" },
          upgradeEvidence: { type: "array", items: { type: "string" } },
          downgradeEvidence: { type: "array", items: { type: "string" } },
        },
      },
      reader_coherence_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "marketReadCopyAligned",
          "supportingEvidenceAligned",
          "riskNoteAligned",
          "gradeCopyContradiction",
          "providerLeakDetected",
          "contradictionReasons",
          "suggestedMarketReadCopy",
          "suggestedSupportingEvidenceCopy",
          "suggestedRiskCopy",
        ],
        properties: {
          marketReadCopyAligned: { type: "boolean" },
          supportingEvidenceAligned: { type: "boolean" },
          riskNoteAligned: { type: "boolean" },
          gradeCopyContradiction: { type: "boolean" },
          providerLeakDetected: { type: "boolean" },
          contradictionReasons: { type: "array", items: { type: "string" } },
          suggestedMarketReadCopy: { type: "string" },
          suggestedSupportingEvidenceCopy: { type: "string" },
          suggestedRiskCopy: { type: "string" },
        },
      },
      slate_balance_flags: {
        type: "object",
        additionalProperties: false,
        required: [
          "overgradedCandidate",
          "undergradedCandidate",
          "promotion_underreach",
          "unsupported_promotion",
          "unsupported_demotion",
          "unsupported_grade_change",
          "grade_action_mismatch",
          "lean_overuse_warning",
          "no_best_angle_review",
          "demotion_machine_warning",
          "grade_dimension_missing",
          "grade_reason_type_missing",
          "grade_reason_mismatch",
          "lean_without_actionable_value",
          "watchlist_with_strong_actionable_value",
          "best_angle_without_clear_thesis",
          "caution_without_material_risk",
          "no_play_with_strong_value_unexplained",
          "market_read_label_wrong_market_type",
          "fi_copy_mentions_missing_splits",
          "fi_missing_split_used_as_negative",
          "fi_generic_no_signal_copy",
          "fi_copy_lacks_prediction_specific_context",
          "copy_overclaims_sharp_signal",
          "provider_or_source_leak",
          "betting_hype_language",
          "generic_copy_detected",
          "copy_not_prediction_specific",
          "copy_missing_primary_reason",
          "possible_demotion_bias",
          "possible_promotion_bias",
          "actionable_slate_collapse",
          "no_undergraded_value_found",
          "too_many_copy_issues_for_member_facing",
        ],
        properties: {
          overgradedCandidate: { type: "boolean" },
          undergradedCandidate: { type: "boolean" },
          promotion_underreach: { type: "boolean" },
          unsupported_promotion: { type: "boolean" },
          unsupported_demotion: { type: "boolean" },
          unsupported_grade_change: { type: "boolean" },
          grade_action_mismatch: { type: "boolean" },
          lean_overuse_warning: { type: "boolean" },
          no_best_angle_review: { type: "boolean" },
          demotion_machine_warning: { type: "boolean" },
          grade_dimension_missing: { type: "boolean" },
          grade_reason_type_missing: { type: "boolean" },
          grade_reason_mismatch: { type: "boolean" },
          lean_without_actionable_value: { type: "boolean" },
          watchlist_with_strong_actionable_value: { type: "boolean" },
          best_angle_without_clear_thesis: { type: "boolean" },
          caution_without_material_risk: { type: "boolean" },
          no_play_with_strong_value_unexplained: { type: "boolean" },
          market_read_label_wrong_market_type: { type: "boolean" },
          fi_copy_mentions_missing_splits: { type: "boolean" },
          fi_missing_split_used_as_negative: { type: "boolean" },
          fi_generic_no_signal_copy: { type: "boolean" },
          fi_copy_lacks_prediction_specific_context: { type: "boolean" },
          copy_overclaims_sharp_signal: { type: "boolean" },
          provider_or_source_leak: { type: "boolean" },
          betting_hype_language: { type: "boolean" },
          generic_copy_detected: { type: "boolean" },
          copy_not_prediction_specific: { type: "boolean" },
          copy_missing_primary_reason: { type: "boolean" },
          possible_demotion_bias: { type: "boolean" },
          possible_promotion_bias: { type: "boolean" },
          actionable_slate_collapse: { type: "boolean" },
          no_undergraded_value_found: { type: "boolean" },
          too_many_copy_issues_for_member_facing: { type: "boolean" },
        },
      },
      safety_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "postgame_data_present",
          "provider_names_present",
          "invented_data_detected",
          "invalid_grade_label",
          "attempted_pick_flip",
          "attempted_probability_change",
          "attempted_projected_score_change",
          "attempted_live_apply_change",
        ],
        properties: {
          postgame_data_present: { type: "boolean" },
          provider_names_present: { type: "boolean" },
          invented_data_detected: { type: "boolean" },
          invalid_grade_label: { type: "boolean" },
          attempted_pick_flip: { type: "boolean" },
          attempted_probability_change: { type: "boolean" },
          attempted_projected_score_change: { type: "boolean" },
          attempted_live_apply_change: { type: "boolean" },
        },
      },
      confidence: { type: "number", minimum: 0, maximum: 1 },
      severity: { type: "string", enum: ["info", "low", "medium", "high", "block"] },
    },
  },
} as const;

export function dailyEdgeIntelligenceSystemPrompt(): string {
  return [
    "You are the OddSphere Daily Edge Intelligence Reviewer.",
    "You strengthen the existing Daily Edge reader; you do not create a new product surface.",
    "Review exactly one prediction/market evidence object.",
    "Use this order: Model/Stats Read, Market Read, Price/Value Read, Data Quality Read, Grade Alignment, Reader Coherence.",
    "The original Play Grade is context only. Do not anchor on it.",
    "Identify both overgraded and undergraded plays. Do not become a demotion machine.",
    "Separate grade-change recommendations from copy improvements. Seeing risk does not automatically mean changing the grade.",
    "Risk can produce Market Read improvement, Supporting Evidence improvement, Risk note improvement, a copy-only recommendation, or a human review flag without changing the grade.",
    "Only recommend a grade change when the grade-change materiality is medium or high and evidence supports the direction.",
    "Low-materiality concerns should usually produce copy/risk/read improvement, not grade change.",
    "A downgrade requires material evidence that copy-only improvement is not enough. A promotion requires clear positive model/value/market evidence.",
    "Mixed market alone usually improves Market Read copy; it is not a downgrade by itself.",
    "Heavy price alone usually creates price-risk copy unless the price truly kills value.",
    "'Not elite enough' is only a downgrade reason when the current grade is Best Angle and the play lacks a top-tier thesis.",
    "Best Angle does not require perfect agreement across model, consensus, sharp-book signal, and movement.",
    "Best Angle means one of the strongest betting positions on the slate because win case, betting value, market context, and read quality combine into a strong overall play.",
    "The public Play Grade system does not change: Best Angle, Lean, Watchlist, Caution, No Play.",
    "Internally, evaluate Play Grade as multidimensional: win case, betting value, market context, price quality, model/stat support, data quality, risk penalty, and read quality.",
    "Do not treat Play Grade as a one-dimensional confidence label, EV label, or win-probability label.",
    "Always assign gradeReasonType to explain why the simple public grade is appropriate.",
    "Best Angle requires a clear betting thesis, playable price/number, manageable risk, and market support OR a clear model/value reason to override market friction.",
    "Block Best Angle for bad/unplayable price, weak win case, weak model/stat support, projection not supporting the pick, market resistance with no override thesis, high-materiality data warning, or risk copy more severe than the grade.",
    "Lean is actionable positive value but not top-tier: good win case with heavier price, good value with mixed market, strong projection with risk, or a playable angle lacking Best Angle conviction.",
    "Watchlist is interesting but not fully actionable: model edge with resistance, market support with thin edge, setup needing better price/line movement, or a monitored undergraded candidate.",
    "Caution means material conflict, fragile data, bad price, stale input, or risk strong enough to make action uncomfortable.",
    "No Play means no actionable edge, weak win case, bad price, insufficient core evidence, or Toss-Up FI.",
    "Grade reason examples: Lean can be model_value_edge or price_capped; Watchlist can be thin_edge_watchlist; Caution can be data_quality_caution; Best Angle can be clean_alignment or model_value_edge; No Play can be bad_price_no_play or fi_toss_up_no_play.",
    "Never flip picks, change probabilities, change projections, or apply grade changes.",
    "Never include postgame results, provider names, internal AI names, or sportsbook/provider jargon in member-facing copy.",
    "For ML and Totals, reconcile Consensus Splits and Sharp Book Splits/Signal when present.",
    "For FI, missing consensus/sharp split bars are expected and low materiality by themselves.",
    "Market Read labels are market-specific. ML/Totals may only use: clean_market_support, consensus_support, sharp_book_support, mixed_but_playable, market_resistance, market_resistance_with_model_value_override, price_capped, no_clear_market_signal, insufficient_core_data.",
    "FI may only use: fi_model_support, fi_price_support, fi_line_movement_support, fi_mixed, fi_data_caution, fi_insufficient_core_data. Do not return fi_no_clear_signal; if FI market context is weak, explain it with prediction-specific model/price/context copy.",
    "Never use FI-prefixed labels for ML/Totals. Never use ML/Total split-source labels for FI unless true FI-specific market signal exists.",
    "FI copy must be prediction-specific and should focus on FI model probability/edge, starter/top-order or early-scoring context when available, price/juice, FI line/price movement, and data/starter confidence.",
    "Do not make missing FI split bars the centerpiece. Do not say splits are unavailable, sharp signal is unavailable, or missing split data lowers confidence.",
    "Avoid repeating generic 'no clear signal' FI copy; use it only when useful and pair it with prediction-specific model/price/context reasoning.",
    "All member-facing copy must be prediction-specific. If copy could apply to any game on the slate, it is too generic.",
    "Avoid provider/source leaks and hype. Do not use: Playbook, SharpAPI, Circa, sharp money loves, sharp money is overwhelmingly on, guaranteed, lock, free money.",
    "Preferred terms: Consensus Splits, Sharp-book split profile, Sharp-book signal, market resistance, mixed but playable, price caps the grade, model/value override.",
    "Return strict JSON matching the provided schema.",
  ].join("\n");
}

export function dailyEdgeIntelligenceUserPayload(evidence: PredictionEvidenceObject) {
  return {
    variant: AI_DAILY_EDGE_INTELLIGENCE_REVIEW_VARIANT,
    task: "Evidence-first Daily Edge intelligence review. Evaluate model/stat support, market read, price/value, grade alignment, and reader coherence. No live changes.",
    evidence,
    validationRules: [
      "If ML/Total has price, model probability, edge, market implied, and consensus/sharp source present, marketReadLabel cannot be insufficient_data.",
      "If FI has price/model/edge/core context, missing consensus/sharp split bars cannot produce insufficient_data.",
      "If suggestedPlayGrade differs from originalPlayGrade, actionVsOriginal must match promote/downgrade.",
      "gradeChangeRecommended and gradeChangeDirection must agree with suggestedPlayGrade versus originalPlayGrade.",
      "If gradeChangeRecommended is true, gradeChangeMateriality must be medium/high and gradeChangeEvidence must be specific.",
      "If gradeChangeMateriality is low or isRiskCopyEnough is true, prefer copyOnlyImprovementRecommended over a grade change.",
      "Flag unsupported_grade_change when a grade change lacks material evidence, conflicts with copy, or copy-only improvement is enough.",
      "Flag unsupported_demotion for generic risk-only downgrades and unsupported_promotion for generic optimism-only promotions.",
      "Populate marketRead/supportingEvidence/riskNote/copyOnly improvement booleans separately from gradeChangeRecommended.",
      "Populate overgradedCandidate, undergradedCandidate, overgradeReason, undergradeReason, upgradeEvidence, and downgradeEvidence.",
      "If demoting, provide a material blocker.",
      "If recommending Best Angle, populate winCaseStrengthScore, bettingValueStrengthScore, marketContextScore, readQualityScore, riskPenaltyScore, bestAngleProfile, and bestAngleThesis.",
      "Always populate all internal grade dimensions: winCaseStrengthScore, bettingValueStrengthScore, marketContextScore, priceQualityScore, modelStatSupportScore, dataQualityScore, riskPenaltyScore, readQualityScore.",
      "Always populate gradeReasonType using the allowed enum.",
      "Flag grade_dimension_missing, grade_reason_type_missing, grade_reason_mismatch, lean_without_actionable_value, watchlist_with_strong_actionable_value, best_angle_without_clear_thesis, caution_without_material_risk, and no_play_with_strong_value_unexplained when applicable.",
      "Best Angle cannot be rejected solely because one market signal is mixed; explain why market friction does or does not block.",
      "Best Angle cannot be recommended without a clear answer for why price does or does not block and why this can be top tier.",
      "If a promotion candidate is held, provide a material blocker or flag promotion_underreach.",
      "Member-facing copy must use only Consensus Splits, Sharp Book Splits, Sharp Book Signal, and Market Read labels.",
      "ML/Totals cannot use FI-prefixed Market Read labels; FI cannot use ML/Total split-source labels unless true FI-specific market signal exists.",
      "Flag market_read_label_wrong_market_type when label family does not match market type.",
      "Flag fi_copy_mentions_missing_splits and fi_missing_split_used_as_negative if FI copy or grade reasoning treats unavailable FI split bars/signals as a downside.",
      "Flag fi_generic_no_signal_copy when FI copy repeats generic no-clear-signal language without model/price/context specifics.",
      "Flag fi_copy_lacks_prediction_specific_context when FI copy omits model edge, price/juice, starter/context, FI movement, or early-offense/team FI stats.",
      "Flag copy_overclaims_sharp_signal, provider_or_source_leak, betting_hype_language, generic_copy_detected, copy_not_prediction_specific, and copy_missing_primary_reason when applicable.",
      "If suggestedPlayGrade changes from originalPlayGrade, actionVsOriginal must match the public grade order: No Play < Caution < Watchlist < Lean < Best Angle.",
    ],
  };
}
