export const AI_MARKET_ANALYST_CURRENT_SCHEMA = {
  name: "oddsphere_market_analyst_current_v1",
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "market_reviews",
      "card_coherence_review",
      "safety_review",
      "recommended_actions",
      "safe_copy_fixes",
      "provider_name_check",
      "confidence",
      "severity",
    ],
    properties: {
      market_reviews: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "market",
            "data_integrity_review",
            "market_read_review",
            "betting_value_review",
            "promotion_candidate_review",
            "play_grade_review",
            "sharp_grade_rebuild",
            "issue_materiality",
            "recommended_actions",
            "safe_copy_fixes",
            "repair_actions",
            "confidence",
            "severity",
          ],
          properties: {
            market: { type: "string", enum: ["moneyline", "total", "first_inning"] },
            data_integrity_review: {
              type: "object",
              additionalProperties: false,
              required: [
                "status",
                "summary",
                "criticalDataIssue",
                "nonCriticalDataWarning",
                "issues",
                "repair_actions",
                "should_affect_grade",
              ],
              properties: {
                status: { type: "string", enum: ["pass", "warn", "block"] },
                summary: { type: "string" },
                criticalDataIssue: { type: "boolean" },
                nonCriticalDataWarning: { type: "boolean" },
                issues: { type: "array", items: { type: "string" } },
                repair_actions: {
                  type: "array",
                  items: {
                    type: "string",
                    enum: [
                      "none",
                      "rerun_fetch",
                      "mark_source_unavailable",
                      "block_card",
                      "repair_mapping",
                      "refresh_lineup_or_starter",
                      "refresh_splits",
                      "review_price",
                    ],
                  },
                },
                should_affect_grade: { type: "boolean" },
              },
            },
            market_read_review: {
              type: "object",
              additionalProperties: false,
              required: [
                "status",
                "summary",
                "currentMarketRead",
                "recommendedMarketRead",
                "memberCopy",
                "reasonCodes",
                "consensusSharpAgreement",
                "lineMovementSignal",
                "marketConflictMateriality",
                "sourceConflict",
              ],
              properties: {
                status: { type: "string", enum: ["pass", "warn", "block"] },
                summary: { type: "string" },
                currentMarketRead: { type: "string" },
                recommendedMarketRead: {
                  type: "string",
                  enum: [
                    "aligned",
                    "mixed",
                    "resistance",
                    "consensus_support",
                    "consensus_resistance",
                    "no_clear_signal",
                    "insufficient_data",
                  ],
                },
                memberCopy: { type: "string" },
                reasonCodes: { type: "array", items: { type: "string" } },
                consensusSharpAgreement: {
                  type: "string",
                  enum: ["agree", "disagree", "consensus_only", "sharp_only", "not_available", "unclear"],
                },
                lineMovementSignal: {
                  type: "string",
                  enum: ["toward_pick", "against_pick", "neutral", "not_available", "unclear"],
                },
                marketConflictMateriality: { type: "string", enum: ["none", "low", "medium", "high"] },
                sourceConflict: { type: "boolean" },
              },
            },
            betting_value_review: {
              type: "object",
              additionalProperties: false,
              required: [
                "status",
                "summary",
                "realModelEdge",
                "pricePlayable",
                "edgeLargeEnoughForGrade",
                "marketResistanceMeaningful",
                "goodBetDespiteMixedSignals",
                "modelPickButNotWorthBetting",
                "disciplinedBettorAction",
                "promotionCandidate",
                "downgradeCandidate",
              ],
              properties: {
                status: { type: "string", enum: ["pass", "warn", "block"] },
                summary: { type: "string" },
                realModelEdge: { type: "boolean" },
                pricePlayable: { type: "boolean" },
                edgeLargeEnoughForGrade: { type: "boolean" },
                marketResistanceMeaningful: { type: "boolean" },
                goodBetDespiteMixedSignals: { type: "boolean" },
                modelPickButNotWorthBetting: { type: "boolean" },
                disciplinedBettorAction: { type: "string", enum: ["pass", "watch", "lean", "play"] },
                promotionCandidate: { type: "boolean" },
                downgradeCandidate: { type: "boolean" },
              },
            },
            promotion_candidate_review: {
              type: "object",
              additionalProperties: false,
              required: [
                "promotionCandidateReviewed",
                "promotionDecision",
                "recommendedGrade",
                "maxReasonableGrade",
                "primaryBlocker",
                "blockerMateriality",
                "evidenceThatSupportsPromotion",
                "evidenceAgainstPromotion",
                "whatWouldNeedToChangeToPromote",
              ],
              properties: {
                promotionCandidateReviewed: { type: "boolean" },
                promotionDecision: { type: "string", enum: ["promote", "hold", "reject"] },
                recommendedGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
                maxReasonableGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
                primaryBlocker: { type: "string" },
                blockerMateriality: { type: "string", enum: ["low", "medium", "high"] },
                evidenceThatSupportsPromotion: { type: "array", items: { type: "string" } },
                evidenceAgainstPromotion: { type: "array", items: { type: "string" } },
                whatWouldNeedToChangeToPromote: { type: "array", items: { type: "string" } },
              },
            },
            play_grade_review: {
              type: "object",
              additionalProperties: false,
              required: [
                "status",
                "summary",
                "currentPlayGrade",
                "recommendedPlayGrade",
                "gradeDirection",
                "bestAngleUpgradeForEvaluationOnly",
              ],
              properties: {
                status: { type: "string", enum: ["pass", "warn", "block"] },
                summary: { type: "string" },
                currentPlayGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
                recommendedPlayGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
                gradeDirection: { type: "string", enum: ["promote", "downgrade", "hold"] },
                bestAngleUpgradeForEvaluationOnly: { type: "boolean" },
              },
            },
            sharp_grade_rebuild: {
              type: "object",
              additionalProperties: false,
              required: [
                "originalPlayGrade",
                "rebuiltPlayGrade",
                "actionVsOriginal",
                "independentSharpScore",
                "bettingValueScore",
                "marketSignalScore",
                "priceQualityScore",
                "modelEdgeScore",
                "dataQualityScore",
                "riskPenalty",
                "slateRankCandidateScore",
                "publicActionability",
                "maxReasonableGrade",
                "evidenceForUpgrade",
                "evidenceForDowngrade",
                "materialBlockers",
                "priceVerdict",
                "marketVerdict",
                "modelEdgeVerdict",
                "finalSharpBettorSummary",
              ],
              properties: {
                originalPlayGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
                rebuiltPlayGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
                actionVsOriginal: { type: "string", enum: ["promote", "downgrade", "hold"] },
                independentSharpScore: { type: "number", minimum: 0, maximum: 100 },
                bettingValueScore: { type: "number", minimum: 0, maximum: 100 },
                marketSignalScore: { type: "number", minimum: 0, maximum: 100 },
                priceQualityScore: { type: "number", minimum: 0, maximum: 100 },
                modelEdgeScore: { type: "number", minimum: 0, maximum: 100 },
                dataQualityScore: { type: "number", minimum: 0, maximum: 100 },
                riskPenalty: { type: "number", minimum: 0, maximum: 100 },
                slateRankCandidateScore: { type: "number", minimum: 0, maximum: 100 },
                publicActionability: { type: "boolean" },
                maxReasonableGrade: { type: "string", enum: ["No Play", "Caution", "Watchlist", "Lean", "Best Angle"] },
                evidenceForUpgrade: { type: "array", items: { type: "string" } },
                evidenceForDowngrade: { type: "array", items: { type: "string" } },
                materialBlockers: { type: "array", items: { type: "string" } },
                priceVerdict: { type: "string" },
                marketVerdict: { type: "string" },
                modelEdgeVerdict: { type: "string" },
                finalSharpBettorSummary: { type: "string" },
              },
            },
            issue_materiality: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                required: ["issue_type", "severity", "materiality_to_bet", "should_affect_grade", "direction", "message"],
                properties: {
                  issue_type: { type: "string" },
                  severity: { type: "string", enum: ["info", "low", "medium", "high", "block"] },
                  materiality_to_bet: { type: "string", enum: ["low", "medium", "high"] },
                  should_affect_grade: { type: "boolean" },
                  direction: { type: "string", enum: ["downgrade", "promote", "hold", "copy_only", "data_repair"] },
                  message: { type: "string" },
                },
              },
            },
            recommended_actions: {
              type: "array",
              items: {
                type: "string",
                enum: ["none", "copy_fix", "recommend_promotion", "recommend_downgrade", "block_card", "repair_data", "hold_grade"],
              },
            },
            safe_copy_fixes: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                required: ["field", "replacement", "reason"],
                properties: {
                  field: { type: "string" },
                  replacement: { type: "string" },
                  reason: { type: "string" },
                },
              },
            },
            repair_actions: {
              type: "array",
              items: {
                type: "string",
                enum: [
                  "none",
                  "rerun_fetch",
                  "mark_source_unavailable",
                  "block_card",
                  "repair_mapping",
                  "refresh_lineup_or_starter",
                  "refresh_splits",
                  "review_price",
                ],
              },
            },
            confidence: { type: "number", minimum: 0, maximum: 1 },
            severity: { type: "string", enum: ["info", "low", "medium", "high", "block"] },
          },
        },
      },
      card_coherence_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "status",
          "summary",
          "quickReadMatchesMarketRead",
          "playGradeMatchesMarketRead",
          "supportingEvidenceMatchesSplits",
          "providerNameLeak",
          "contradictions",
        ],
        properties: {
          status: { type: "string", enum: ["pass", "warn", "block"] },
          summary: { type: "string" },
          quickReadMatchesMarketRead: { type: "boolean" },
          playGradeMatchesMarketRead: { type: "boolean" },
          supportingEvidenceMatchesSplits: { type: "boolean" },
          providerNameLeak: { type: "boolean" },
          contradictions: { type: "array", items: { type: "string" } },
        },
      },
      safety_review: {
        type: "object",
        additionalProperties: false,
        required: [
          "postgame_data_present",
          "provider_names_present",
          "invented_data_detected",
          "invalid_grade_label",
          "attempted_pick_flip",
          "attempted_probability_change",
          "attempted_projected_score_change",
          "attempted_live_apply_change",
        ],
        properties: {
          postgame_data_present: { type: "boolean" },
          provider_names_present: { type: "boolean" },
          invented_data_detected: { type: "boolean" },
          invalid_grade_label: { type: "boolean" },
          attempted_pick_flip: { type: "boolean" },
          attempted_probability_change: { type: "boolean" },
          attempted_projected_score_change: { type: "boolean" },
          attempted_live_apply_change: { type: "boolean" },
        },
      },
      recommended_actions: {
        type: "array",
        items: {
          type: "string",
          enum: ["none", "copy_fix", "recommend_promotion", "recommend_downgrade", "block_card", "repair_data", "hold_grade"],
        },
      },
      safe_copy_fixes: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["market", "field", "replacement", "reason"],
          properties: {
            market: { type: "string", enum: ["moneyline", "total", "first_inning", "card"] },
            field: { type: "string" },
            replacement: { type: "string" },
            reason: { type: "string" },
          },
        },
      },
      provider_name_check: {
        type: "object",
        additionalProperties: false,
        required: ["provider_names_present", "offending_terms"],
        properties: {
          provider_names_present: { type: "boolean" },
          offending_terms: { type: "array", items: { type: "string" } },
        },
      },
      confidence: { type: "number", minimum: 0, maximum: 1 },
      severity: { type: "string", enum: ["info", "low", "medium", "high", "block"] },
    },
  },
  strict: true,
} as const;
