-- ═════════════════════════════════════════════════════════════════════════════
-- Oddsphere · Schema Migration V11 — source_type provenance tracking
-- ═════════════════════════════════════════════════════════════════════════════
--
-- WHY
--   V2.1's data-mode strategy (Part 2) supports three provenances for any
--   prediction:
--     mock     — generated by Phase 6's MockOddsProvider / MockSharpSignalProvider
--                / etc. The default during V1 launch.
--     manual   — pasted in by Daniel via the Phase 7.25 Admin Manual Upload
--                tool. Used to launch with real picks while paid APIs are off.
--     real_api — pulled from a live paid feed in Phase 8.
--
--   Capturing provenance on every row lets tracking and audit answer "which
--   of these picks came from a paid feed and which from mock data?" without
--   re-running provider state. It's also the column the V12 admin_audit_log
--   tags so admin actions are attributable to a data mode.
--
-- SHAPE
--   source_type TEXT, NOT NULL, DEFAULT 'mock'. CHECK constraint on the
--   3-value vocabulary: mock / manual / real_api.
--
-- COMPATIBILITY
--   ✓ Existing rows backfill to 'mock' via the column default — accurate,
--     because every row in V1 launch state IS from mock providers.
--   ✓ Existing INSERT paths keep working without code changes; new inserts
--     get 'mock' from the default. Phase 7.25 (manual) and Phase 8 (real_api)
--     code paths will explicitly set source_type when they ship.
--
-- ROLLBACK
--   ALTER TABLE game_predictions DROP COLUMN source_type;
--   ALTER TABLE prop_predictions DROP COLUMN source_type;
--   ALTER TABLE prediction_results DROP COLUMN source_type;
-- ═════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ── game_predictions.source_type ──────────────────────────────────────────
ALTER TABLE game_predictions
  ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT 'mock';

ALTER TABLE game_predictions
  DROP CONSTRAINT IF EXISTS game_predictions_source_type_chk;
ALTER TABLE game_predictions
  ADD CONSTRAINT game_predictions_source_type_chk
  CHECK (source_type IN ('mock', 'manual', 'real_api'));

COMMENT ON COLUMN game_predictions.source_type IS
  'Data provenance for this prediction. mock = MockOddsProvider/etc (V1 default), manual = admin-pasted via Phase 7.25 tool, real_api = paid feed (Phase 8). Existing rows backfill to mock since that''s what generated them.';

-- ── prop_predictions.source_type ──────────────────────────────────────────
ALTER TABLE prop_predictions
  ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT 'mock';

ALTER TABLE prop_predictions
  DROP CONSTRAINT IF EXISTS prop_predictions_source_type_chk;
ALTER TABLE prop_predictions
  ADD CONSTRAINT prop_predictions_source_type_chk
  CHECK (source_type IN ('mock', 'manual', 'real_api'));

COMMENT ON COLUMN prop_predictions.source_type IS
  'Data provenance for this prop prediction. Same vocabulary as game_predictions.source_type.';

-- ── prediction_results.source_type ────────────────────────────────────────
ALTER TABLE prediction_results
  ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT 'mock';

ALTER TABLE prediction_results
  DROP CONSTRAINT IF EXISTS prediction_results_source_type_chk;
ALTER TABLE prediction_results
  ADD CONSTRAINT prediction_results_source_type_chk
  CHECK (source_type IN ('mock', 'manual', 'real_api'));

COMMENT ON COLUMN prediction_results.source_type IS
  'Data provenance carried forward from the prediction at resolve time, so tracking can segment ROI/hit-rate by source without rejoining predictions.';

COMMIT;

-- ═════════════════════════════════════════════════════════════════════════════
-- Verification queries (run after BEGIN..COMMIT succeeds):
--
-- 1. Columns + defaults present on all three tables:
--    SELECT table_name, column_name, data_type, column_default, is_nullable
--    FROM information_schema.columns
--    WHERE table_name IN ('game_predictions', 'prop_predictions', 'prediction_results')
--      AND column_name = 'source_type'
--    ORDER BY table_name;
--
-- 2. CHECK constraints registered:
--    SELECT conname, pg_get_constraintdef(oid)
--    FROM pg_constraint
--    WHERE conname IN (
--      'game_predictions_source_type_chk',
--      'prop_predictions_source_type_chk',
--      'prediction_results_source_type_chk'
--    );
--
-- 3. Backfill: every existing row reads 'mock':
--    SELECT 'game_predictions' AS tbl, source_type, COUNT(*) AS rows
--    FROM game_predictions GROUP BY source_type
--    UNION ALL SELECT 'prop_predictions', source_type, COUNT(*) FROM prop_predictions GROUP BY source_type
--    UNION ALL SELECT 'prediction_results', source_type, COUNT(*) FROM prediction_results GROUP BY source_type
--    ORDER BY tbl, source_type;
--
-- 4. Bad value rejected (this should ERROR):
--    UPDATE game_predictions SET source_type = 'spreadsheet' WHERE id = (SELECT id FROM game_predictions LIMIT 1);
-- ═════════════════════════════════════════════════════════════════════════════
