"use client";

import { useEffect, useMemo, useState } from "react";
import { PlayerPropReaderDialog } from "./PlayerPropReaderDialog";
import type { NflPlayerPropsProductionSnapshot } from "@/lib/services/football/nflPlayerPropsProductionContract";
import type { NflPlayerPropsGrade, NflPlayerPropsRuntimeDecision as Row } from "@/lib/services/football/nflPlayerPropsRuntime";

type GradeFilter = "All" | Exclude<NflPlayerPropsGrade, "Held">;

export function NflPlayerPropsDashboard({ snapshot, reviewMode = false, initialSelectedKey = null }: { snapshot: NflPlayerPropsProductionSnapshot | null; reviewMode?: boolean; initialSelectedKey?: string | null }) {
  const [grade, setGrade] = useState<GradeFilter>("All");
  const [market, setMarket] = useState("all");
  const [search, setSearch] = useState("");
  const [selectedKey, setSelectedKey] = useState<string | null>(initialSelectedKey);
  const allRows = snapshot?.memberDecisions ?? [];
  const markets = useMemo(() => [...new Set(allRows.map((row) => row.market))].sort(), [allRows]);
  const rows = useMemo(() => allRows.filter((row) => (
    (grade === "All" || row.grade === grade)
    && (market === "all" || row.market === market)
    && (!search.trim() || `${row.playerName} ${row.team} ${row.market}`.toLowerCase().includes(search.trim().toLowerCase()))
  )).sort((a, b) => rank(a) - rank(b) || b.expectedValue - a.expectedValue), [allRows, grade, market, search]);
  const topRated = useMemo(() => [...allRows]
    .filter((row) => row.grade === "Best Angle" || row.grade === "Lean")
    .sort((a, b) => rank(a) - rank(b) || b.expectedValue - a.expectedValue)[0] ?? null, [allRows]);
  const worthALook = useMemo(() => [...allRows]
    .filter((row) => key(row) !== (topRated ? key(topRated) : "") && (row.grade === "Lean" || row.grade === "Watchlist"))
    .sort((a, b) => rank(a) - rank(b) || b.expectedValue - a.expectedValue)
    .slice(0, 4), [allRows, topRated]);
  const selected = allRows.find((row) => key(row) === selectedKey) ?? null;

  useEffect(() => {
    const url = new URL(window.location.href);
    if (selectedKey) url.searchParams.set("reader", selectedKey);
    else url.searchParams.delete("reader");
    window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
  }, [selectedKey]);

  if (!snapshot) return <EmptyBoard reviewMode={reviewMode} />;

  return <section className="mx-auto max-w-7xl px-4 pb-16 pt-6 sm:px-6 lg:px-8" data-review-surface={reviewMode ? "nfl-player-props" : undefined}>
    {reviewMode ? <div className="mb-4 rounded-lg border border-amber-300/20 bg-amber-300/[0.05] px-4 py-3 text-xs leading-5 text-amber-50/90"><strong className="font-black uppercase tracking-wider">Private founder review</strong> · Real timestamped Week 1 prices and model outputs. Publication, member refresh, and official tracking remain disabled.</div> : null}
    <BoardHeader snapshot={snapshot} reviewMode={reviewMode} />
    {topRated ? <TopRated row={topRated} onSelect={() => setSelectedKey(key(topRated))} /> : null}
    {worthALook.length ? <WorthALook rows={worthALook} onSelect={setSelectedKey} /> : null}
    <MarketBrowser rows={allRows} markets={markets} activeMarket={market} onMarket={(value) => { setMarket(value); setGrade("All"); focusBoard(); }} />
    <section id="nfl-props-board" className="mt-8 scroll-mt-24" data-product-zone="all-props">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-widest text-violet-300">All props</p><h2 className="mt-1 text-2xl font-black text-white">Build your board</h2><p className="mt-1 text-xs leading-5 text-gray-500">Browse every complete exact-price read, then open the player reader for the full model case.</p></div><p className="text-xs text-gray-500"><strong className="text-gray-200">{rows.length}</strong> shown · {allRows.length} graded</p></div>
      <SignalRail snapshot={snapshot} onGrade={(value) => { setGrade(value); focusBoard(); }} />
      <div className="mt-3 rounded-xl border border-gray-800 bg-[#0d1016] p-3 sm:p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex gap-2 overflow-x-auto pb-1" aria-label="Market filters"><FilterButton active={market === "all"} onClick={() => setMarket("all")}>All markets</FilterButton>{markets.map((value) => <FilterButton key={value} active={market === value} onClick={() => setMarket(value)}>{label(value)}</FilterButton>)}</div>
        <div className="flex flex-col gap-2 sm:flex-row"><select aria-label="Grade filter" value={grade} onChange={(event) => setGrade(event.target.value as GradeFilter)} className="h-10 rounded-md border border-gray-700 bg-gray-950 px-3 text-xs font-bold text-gray-200">{(["All", "Best Angle", "Lean", "Watchlist", "No Play"] as GradeFilter[]).map((value) => <option key={value}>{value}</option>)}</select><input aria-label="Search players" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search player, team, or market" className="h-10 min-w-56 rounded-md border border-gray-700 bg-gray-950 px-3 text-sm text-white placeholder:text-gray-600" /></div>
      </div></div>
    </section>
    {rows.length ? <><div className="mt-3 hidden overflow-hidden rounded-lg border border-gray-800 xl:block"><BoardTable rows={rows} selectedKey={selectedKey} onSelect={setSelectedKey} /></div><div className="mt-3 grid gap-3 xl:hidden">{rows.map((row) => <BoardCard key={key(row)} row={row} active={selectedKey === key(row)} onSelect={() => setSelectedKey(key(row))} />)}</div></> : <div className="mt-3 rounded-lg border border-gray-800 p-8 text-center text-sm text-gray-500">No props match these filters.</div>}
    <details className="mt-6 rounded-lg border border-gray-800 bg-black/20 px-4 py-3 text-xs leading-5 text-gray-500"><summary className="cursor-pointer font-bold text-gray-300">Board coverage & availability</summary><p className="mt-2">{snapshot.board.diagnostics.unavailableNoIndependentBenchmark} exact outcomes lack a separate same-line market benchmark and {snapshot.board.diagnostics.incompleteExactOffers} raw offers lack a complete line/price pair, so neither group is graded or shown. The {snapshot.board.counts.Held} Held outcomes have genuine player-role or identity ambiguity and remain audit-only.</p></details>
    {selected ? <PropReader row={selected} allRows={allRows} onClose={() => setSelectedKey(null)} /> : null}
  </section>;
}

function TopRated({ row, onSelect }: { row: Row; onSelect: () => void }) {
  return <section className="border-b border-gray-800 py-7" data-product-zone="top-rated"><div className="mb-4"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-emerald-300">Top Rated</p><h2 className="mt-1 text-2xl font-black text-white">Our strongest model read</h2></div><article className="relative overflow-hidden rounded-xl border border-emerald-400/25 bg-[radial-gradient(circle_at_top_right,rgba(52,211,153,0.13),transparent_42%),linear-gradient(145deg,#111820,#0b0e14_68%)] p-5 sm:p-6"><div className="grid gap-6 lg:grid-cols-[minmax(0,1.15fr)_minmax(280px,0.85fr)] lg:items-stretch"><div><div className="flex flex-wrap items-center gap-2"><GradeBadge grade={row.grade} /><span className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{row.team} · {label(row.market)}</span></div><h3 className="mt-4 text-3xl font-black text-white sm:text-4xl">{row.playerName}</h3><div className="mt-4 flex flex-wrap items-end gap-x-8 gap-y-4"><div><p className="text-[9px] font-black uppercase text-gray-600">Model pick</p><p className="mt-1 text-3xl font-black text-white">{selection(row)}</p></div><div><p className="text-[9px] font-black uppercase text-gray-600">Best price</p><p className="mt-1 text-2xl font-black text-emerald-300">{price(row.americanPrice)}</p><p className="text-[10px] text-gray-500">{book(row.sportsbook)}</p></div></div><div className="mt-5 grid grid-cols-3 overflow-hidden rounded-lg border border-white/[0.07] bg-black/20"><HeroMetric label="Model chance" value={pct(row.finalProbability)} /><HeroMetric label="Model edge" value={signedPct(row.probabilityEdge)} positive={row.probabilityEdge > 0} /><HeroMetric label="Expected value" value={signedPct(row.expectedValue)} positive={row.expectedValue > 0} /></div></div><div className="flex flex-col rounded-lg border border-white/[0.08] bg-black/25 p-4 sm:p-5"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-violet-300">Our Model Read</p><p className="mt-3 flex-1 text-sm font-semibold leading-7 text-gray-100">{modelRead(row)}</p><div className="mt-4 border-t border-gray-800 pt-4"><p className="text-xs text-gray-500">Role confidence <strong className="ml-1 text-white">{pct(row.participationProbability)}</strong></p><button type="button" onClick={onSelect} className="mt-4 h-10 w-full rounded-md bg-white px-4 text-xs font-black text-gray-950 transition hover:bg-emerald-200">Open Full Reader</button></div></div></div></article></section>;
}

function WorthALook({ rows, onSelect }: { rows: Row[]; onSelect: (value: string) => void }) {
  return <section className="border-b border-gray-800 py-7" data-product-zone="worth-a-look"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-amber-300">Worth a Look</p><h2 className="mt-1 text-2xl font-black text-white">More model reads on the radar</h2></div><span className="text-xs text-gray-500">{rows.length} reads</span></div><div className="mt-4 flex snap-x gap-3 overflow-x-auto pb-2">{rows.map((row) => <article key={key(row)} className="w-[min(86vw,330px)] shrink-0 snap-start rounded-lg border border-gray-800 bg-[#0e1218] p-4"><div className="flex items-start justify-between gap-3"><span><strong className="block text-base text-white">{row.playerName}</strong><span className="mt-1 block text-xs text-gray-500">{row.team} · {label(row.market)}</span></span><GradeBadge grade={row.grade} /></div><div className="mt-5 flex items-end justify-between gap-3"><span><span className="block text-[9px] font-bold uppercase text-gray-600">Model pick</span><strong className="mt-1 block text-xl text-white">{selection(row)}</strong></span><span className="text-right"><span className="block text-[9px] font-bold uppercase text-gray-600">Best price</span><strong className="mt-1 block text-lg text-white">{price(row.americanPrice)}</strong><span className="block text-[10px] text-gray-500">{book(row.sportsbook)}</span></span></div><p className="mt-4 border-y border-gray-800 py-3 text-xs leading-5 text-gray-400">{modelRead(row)}</p><button type="button" onClick={() => onSelect(key(row))} className="mt-3 h-9 w-full rounded-md border border-gray-700 text-xs font-black text-gray-100 hover:border-violet-400 hover:bg-violet-500/10">Open Reader</button></article>)}</div></section>;
}

function MarketBrowser({ rows, markets, activeMarket, onMarket }: { rows: Row[]; markets: string[]; activeMarket: string; onMarket: (value: string) => void }) {
  return <section className="border-b border-gray-800 py-7" data-product-zone="markets"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-violet-300">Markets</p><h2 className="mt-1 text-2xl font-black text-white">Find the prop you want</h2><p className="mt-1 text-xs leading-5 text-gray-500">Every market is modeled and calibrated in its own statistical lane.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"><button type="button" onClick={() => onMarket("all")} aria-pressed={activeMarket === "all"} className={`rounded-lg border p-4 text-left transition ${activeMarket === "all" ? "border-violet-400 bg-violet-500/10" : "border-gray-800 bg-[#0e1218] hover:border-gray-700"}`}><span className="text-[9px] font-black uppercase text-violet-300">Full board</span><strong className="mt-1 block text-base text-white">All NFL props</strong><span className="mt-2 block text-xs text-gray-500">{rows.length} graded reads</span></button>{markets.map((value) => { const marketRows = rows.filter((row) => row.market === value); const strongest = [...marketRows].sort((a, b) => rank(a) - rank(b))[0]; return <button type="button" key={value} onClick={() => onMarket(value)} aria-pressed={activeMarket === value} className={`rounded-lg border p-4 text-left transition ${activeMarket === value ? "border-violet-400 bg-violet-500/10" : "border-gray-800 bg-[#0e1218] hover:-translate-y-0.5 hover:border-gray-700"}`}><span className="text-[9px] font-black uppercase text-gray-600">Player market</span><strong className="mt-1 block text-base text-white">{label(value)}</strong><span className="mt-2 flex items-center justify-between text-xs text-gray-500"><span>{marketRows.length} props</span>{strongest ? <span className={strongest.grade === "Best Angle" ? "text-emerald-300" : strongest.grade === "Watchlist" ? "text-amber-300" : "text-gray-400"}>{strongest.grade}</span> : null}</span></button>; })}</div></section>;
}

function HeroMetric({ label: title, value, positive = false }: { label: string; value: string; positive?: boolean }) { return <div className="border-r border-white/[0.07] px-3 py-3 last:border-r-0 sm:px-4"><span className="block text-[8px] font-black uppercase tracking-wider text-gray-600">{title}</span><strong className={`mt-1 block text-sm sm:text-lg ${positive ? "text-emerald-300" : "text-white"}`}>{value}</strong></div>; }

function BoardHeader({ snapshot, reviewMode }: { snapshot: NflPlayerPropsProductionSnapshot; reviewMode: boolean }) {
  return <header className="overflow-hidden rounded-xl border border-violet-400/20 bg-[radial-gradient(circle_at_top_right,rgba(139,92,246,0.16),transparent_42%),linear-gradient(145deg,#11151d,#090b10_68%)] p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-bold text-emerald-300">NFL · Week {snapshot.week}</span><span className="rounded border border-violet-400/30 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-violet-200">{reviewMode ? "Production candidate" : "NFL model"}</span>{reviewMode ? <span className="rounded border border-amber-400/30 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-amber-200">Review only</span> : null}</div><h1 className="mt-2 text-3xl font-black tracking-tight text-white sm:text-4xl">NFL Player Props</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-400">Start with the top-rated play, scan the model reads worth a look, then explore every market and exact offered price.</p></div><div className="rounded-lg border border-white/[0.08] bg-black/25 px-4 py-3 md:text-right"><p className="text-[9px] font-black uppercase tracking-wider text-gray-600">Board status</p><p className="mt-1 text-sm font-black text-emerald-300">Prices updated {localTime(snapshot.board.evaluatedAt)}</p><p className="mt-1 text-[10px] text-gray-600">Exact offered price · updates until T-60</p></div></div><div className="mt-5 grid grid-cols-3 gap-2"><SlateMetric label="Best angles" value={snapshot.board.counts["Best Angle"]} tone="best" /><SlateMetric label="Worth a look" value={snapshot.board.counts.Lean + snapshot.board.counts.Watchlist} tone="look" /><SlateMetric label="Markets" value={new Set(snapshot.memberDecisions.map((row) => row.market)).size} tone="market" /></div></header>;
}

function SlateMetric({ label: title, value, tone }: { label: string; value: number; tone: "best" | "look" | "market" }) { const style = tone === "best" ? "border-emerald-400/25 bg-emerald-400/[0.07] text-emerald-200" : tone === "look" ? "border-amber-400/25 bg-amber-400/[0.07] text-amber-200" : "border-violet-400/25 bg-violet-400/[0.07] text-violet-200"; return <div className={`rounded-lg border px-3 py-3 sm:px-4 ${style}`}><strong className="block text-xl font-black tabular-nums sm:text-2xl">{value}</strong><span className="mt-0.5 block text-[8px] font-black uppercase tracking-wider text-gray-500 sm:text-[9px]">{title}</span></div>; }

function SignalRail({ snapshot, onGrade }: { snapshot: NflPlayerPropsProductionSnapshot; onGrade: (grade: GradeFilter) => void }) {
  const items: Array<[GradeFilter, string, string, number, string]> = [["Best Angle", "Best Angles", "Strongest stable subgroup", snapshot.board.counts["Best Angle"], "text-emerald-300"], ["Lean", "Leans", "Evidence-backed positive EV", snapshot.board.counts.Lean, "text-sky-300"], ["Watchlist", "Watchlist", "Coherent near-edge", snapshot.board.counts.Watchlist, "text-amber-300"], ["No Play", "No Play", "Complete but below threshold", snapshot.board.counts["No Play"], "text-gray-300"]];
  return <div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{items.map(([grade, title, detail, value, tone]) => <button type="button" key={grade} onClick={() => onGrade(grade)} className="rounded-lg border border-gray-800 bg-[#0e1218] p-4 text-left transition hover:-translate-y-0.5 hover:border-violet-400/40"><span className={`text-2xl font-black ${tone}`}>{value}</span><span className="mt-1 block text-xs font-black uppercase tracking-wider text-white">{title}</span><span className="mt-1 block text-[10px] text-gray-600">{detail}</span></button>)}</div>;
}

function BoardTable({ rows, selectedKey, onSelect }: { rows: Row[]; selectedKey: string | null; onSelect: (key: string) => void }) {
  return <div><div className="grid grid-cols-[1.35fr_1fr_0.8fr_0.7fr_0.7fr_0.7fr_0.85fr] gap-3 border-b border-gray-800 bg-[#151922] px-4 py-3 text-[9px] font-black uppercase tracking-wider text-gray-600"><span>Player / market</span><span>Prediction</span><span>Price</span><span>Projection</span><span>Model</span><span>Edge / EV</span><span>Grade</span></div><div className="divide-y divide-gray-800">{rows.map((row) => <button type="button" key={key(row)} onClick={() => onSelect(key(row))} className={`grid w-full grid-cols-[1.35fr_1fr_0.8fr_0.7fr_0.7fr_0.7fr_0.85fr] items-center gap-3 px-4 py-3 text-left hover:bg-gray-900 ${selectedKey === key(row) ? "bg-violet-400/10" : ""}`}><span className="min-w-0"><strong className="block truncate text-sm text-white">{row.playerName}</strong><span className="mt-0.5 block truncate text-[10px] text-gray-500">{row.team} · {label(row.market)}</span></span><strong className="text-sm text-white">{selection(row)}</strong><span><strong className="block text-sm text-white">{price(row.americanPrice)}</strong><span className="text-[9px] text-gray-600">{book(row.sportsbook)}</span></span><span className="text-xs font-bold text-gray-300">{row.projection === null ? "TD lane" : row.projection.toFixed(1)}</span><span className="text-xs font-black text-violet-200">{pct(row.finalProbability)}</span><span className="text-xs"><strong className={row.probabilityEdge > 0 ? "text-emerald-300" : "text-gray-400"}>{signedPct(row.probabilityEdge)}</strong><span className="mt-0.5 block text-[9px] text-gray-600">{signedPct(row.expectedValue)} EV</span></span><GradeBadge grade={row.grade} /></button>)}</div></div>;
}

function BoardCard({ row, active, onSelect }: { row: Row; active: boolean; onSelect: () => void }) {
  return <button type="button" onClick={onSelect} className={`rounded-lg border p-4 text-left ${active ? "border-violet-400 bg-violet-400/10" : "border-gray-800 bg-[#0e1218]"}`}><span className="flex items-start justify-between gap-3"><span className="min-w-0"><strong className="block truncate text-sm text-white">{row.playerName}</strong><span className="mt-0.5 block truncate text-xs text-gray-500">{row.team} · {label(row.market)}</span></span><GradeBadge grade={row.grade} /></span><span className="mt-4 grid grid-cols-[1fr_auto] items-end gap-3"><span><span className="block text-[9px] font-bold uppercase text-gray-600">Prediction</span><strong className="mt-1 block text-xl text-white">{selection(row)}</strong></span><span className="text-right"><span className="block text-[9px] font-bold uppercase text-gray-600">Best price</span><strong className="mt-1 block text-lg text-white">{price(row.americanPrice)}</strong><span className="block text-[10px] text-gray-500">{book(row.sportsbook)}</span></span></span><span className="mt-4 grid grid-cols-3 border-y border-gray-800 py-3"><Metric title="Projection" value={row.projection === null ? "TD lane" : row.projection.toFixed(1)} /><Metric title="Model edge" value={signedPct(row.probabilityEdge)} positive={row.probabilityEdge > 0} /><Metric title="Expected value" value={signedPct(row.expectedValue)} positive={row.expectedValue > 0} /></span><span className="mt-3 flex h-9 items-center justify-center rounded-md border border-gray-700 text-xs font-bold text-gray-200">Open Reader</span></button>;
}

function PropReader({ row, allRows, onClose }: { row: Row; allRows: Row[]; onClose: () => void }) {
  const comparisons = allRows.filter((other) => other.gameId === row.gameId && other.playerName === row.playerName && other.market === row.market && other.line === row.line && other.side === row.side).sort((a, b) => b.americanPrice - a.americanPrice);
  return <PlayerPropReaderDialog ariaLabel={`${row.playerName} prop details`} title={row.playerName} onClose={onClose}>
    <div className="grid min-w-0 gap-4 p-4 sm:p-6 lg:grid-cols-2">
      <div className="min-w-0 lg:col-span-2"><ReaderPanel title="Prop Summary"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm text-gray-500">{row.team} · {label(row.market)}</span>{row.state === "locked" ? <LockBadge lockedAt={row.lockAt} /> : null}</div><p className="mt-3 text-3xl font-black text-white">{selection(row)} <span className="text-emerald-300">{price(row.americanPrice)}</span></p><p className="mt-1 text-xs text-gray-500">{book(row.sportsbook)} · price observed {localTime(row.observedAt)}</p></div><GradeBadge grade={row.grade} /></div></ReaderPanel></div>
      <div className="min-w-0 lg:col-span-2"><ReaderPanel title="Reader Summary"><p className="max-w-3xl text-base font-semibold leading-7 text-gray-100">{modelRead(row)}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t border-gray-800 pt-3 text-xs"><span className="text-gray-500">Signal <strong className="ml-1 text-gray-200">{row.grade}</strong></span><span className="text-gray-500">Role confidence <strong className="ml-1 text-gray-200">{pct(row.participationProbability)}</strong></span><span className="text-gray-500">Updated <strong className="ml-1 text-gray-200">{localTime(row.observedAt)}</strong></span><span className="text-gray-500">{row.state === "locked" ? "Locked" : "Locks"} <strong className="ml-1 text-gray-200">{localTime(row.lockAt)}</strong></span></div></ReaderPanel></div>
      <ReaderPanel title="Model Comparison"><ProbabilityVisual row={row} /><div className="mt-3 grid grid-cols-3 gap-2"><Metric title="Model edge" value={signedPct(row.probabilityEdge)} positive={row.probabilityEdge > 0} /><Metric title="Expected value" value={signedPct(row.expectedValue)} positive={row.expectedValue > 0} /><Metric title="Model chance" value={pct(row.finalProbability)} /></div></ReaderPanel>
      <ReaderPanel title={row.projection === null ? "Touchdown Probability" : "Projection vs Line"}><ProjectionVisual row={row} /></ReaderPanel>
      <ReaderPanel title="Best Available Price"><div className="overflow-hidden rounded-lg border border-gray-800">{comparisons.map((value, index) => <div key={key(value)} className={`flex items-center justify-between border-b border-gray-800 px-3 py-3 last:border-b-0 ${index === 0 ? "bg-emerald-400/5" : ""}`}><span><strong className="block text-xs text-white">{book(value.sportsbook)}</strong>{index === 0 ? <span className="text-[9px] font-black uppercase text-emerald-300">Best price</span> : null}</span><span className="text-right"><strong className="block text-white">{price(value.americanPrice)}</strong><span className="text-[9px] text-gray-600">{pct(impliedProbability(value.americanPrice))} implied</span></span></div>)}</div></ReaderPanel>
      <ReaderPanel title="Role Confidence"><div className="rounded-lg border border-gray-800 bg-black/20 p-4"><p className="text-2xl font-black text-white">{pct(row.participationProbability)}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-gray-800"><span className="block h-full rounded-full bg-sky-400" style={{ width: `${row.participationProbability * 100}%` }} /></div><p className="mt-3 text-xs leading-5 text-gray-500">Timestamped roster, injury, and expected-role inputs. Material changes recompute before T-60.</p></div></ReaderPanel>
      <ReaderPanel title="What Could Change"><p className="text-sm leading-6 text-gray-200">A material price, role, roster, or injury update triggers a fresh decision while this prop is unlocked. At T-60, the exact model, line, side, sportsbook price, and grade freeze for official tracking.</p></ReaderPanel>
      <ReaderPanel title="Decision Status"><div className="rounded-lg border border-violet-400/20 bg-violet-400/[0.05] p-4 text-xs leading-5 text-gray-400"><strong className="text-violet-200">Exact-price decision:</strong> {pct(row.finalProbability)} calibrated probability at {price(row.americanPrice)} produces {signedPct(row.expectedValue)} expected value. The independent market is context, not a copied prediction head.</div></ReaderPanel>
      <p className="min-w-0 break-words text-[10px] leading-5 text-gray-600 lg:col-span-2">Model {row.modelRelease} · calibration {row.calibrationRelease} · decision {row.decisionRelease} · {row.state === "locked" ? "frozen at T-60" : `locks ${localTime(row.lockAt)}`}</p>
    </div>
  </PlayerPropReaderDialog>;
}

function ProjectionVisual({ row }: { row: Row }) { if (row.projection === null) return <div className="rounded-lg border border-gray-800 bg-black/20 p-4 text-sm leading-6 text-gray-300">Anytime-touchdown probability is a rare-event lane using participation, routes/carries, red-zone opportunity, team touchdown expectation, opponent context, and exact price.</div>; const high = Math.max(row.projection, row.line) * 1.25 || 1; const position = (value: number) => `${Math.max(4, Math.min(96, value / high * 100))}%`; return <div className="rounded-lg border border-gray-800 bg-black/20 p-4"><div className="flex justify-between gap-2 text-xs"><span className="text-gray-500">Projection <strong className="text-white">{row.projection.toFixed(1)}</strong></span><span className="font-bold text-sky-300">Favors {row.projection > row.line ? "Over" : "Under"}</span><span className="text-gray-500">Line <strong className="text-white">{row.line}</strong></span></div><div className="relative mt-6 h-2 rounded-full bg-gray-800"><span className="absolute -top-1.5 h-5 w-0.5 bg-white" style={{ left: position(row.line) }} /><span className="absolute -top-1 h-4 w-4 -translate-x-1/2 rounded-full border-2 border-gray-950 bg-sky-400" style={{ left: position(row.projection) }} /></div></div>; }
function ProbabilityVisual({ row }: { row: Row }) { return <div className="rounded-lg border border-gray-800 bg-black/20 p-4"><ProbabilityBar title="OddSphere calibrated" value={row.finalProbability} tone="bg-violet-400" /><div className="mt-4"><ProbabilityBar title="Independent market" value={row.marketProbability} tone="bg-sky-400" /></div><div className="mt-4 flex justify-between border-t border-gray-800 pt-3 text-xs"><span className="text-gray-500">Probability edge</span><strong className={row.probabilityEdge > 0 ? "text-emerald-300" : "text-gray-300"}>{signedPct(row.probabilityEdge)}</strong></div></div>; }
function ProbabilityBar({ title, value, tone }: { title: string; value: number; tone: string }) { return <div><div className="flex justify-between text-xs"><span className="text-gray-400">{title}</span><strong className="text-white">{pct(value)}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-gray-800"><span className={`block h-full rounded-full ${tone}`} style={{ width: `${value * 100}%` }} /></div></div>; }
function ReaderPanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="min-w-0"><p className="mb-3 text-[10px] font-black uppercase tracking-wider text-gray-500">{title}</p>{children}</section>; }
function LockBadge({ lockedAt }: { lockedAt: string }) { return <span className="inline-flex rounded border border-sky-400/30 bg-sky-400/10 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-sky-200">Locked T-60 · {localTime(lockedAt)}</span>; }
function FilterButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} aria-pressed={active} className={`h-9 shrink-0 rounded-md border px-3 text-xs font-bold ${active ? "border-violet-400 bg-violet-500/15 text-white" : "border-gray-700 bg-gray-950 text-gray-400 hover:text-white"}`}>{children}</button>; }
function GradeBadge({ grade }: { grade: Row["grade"] }) { const style = grade === "Best Angle" ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-300" : grade === "Lean" ? "border-sky-400/40 bg-sky-400/10 text-sky-300" : grade === "Watchlist" ? "border-amber-400/40 bg-amber-400/10 text-amber-300" : "border-gray-700 bg-gray-900 text-gray-400"; return <span className={`inline-flex w-fit rounded border px-2 py-1 text-[9px] font-black uppercase tracking-wider ${style}`}>{grade}</span>; }
function Metric({ title, value, positive = false }: { title: string; value: string; positive?: boolean }) { return <span className="text-center"><span className="block text-[8px] font-bold uppercase text-gray-600">{title}</span><strong className={`mt-1 block text-xs ${positive ? "text-emerald-300" : "text-gray-200"}`}>{value}</strong></span>; }
function EmptyBoard({ reviewMode }: { reviewMode: boolean }) { return <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="border-y border-gray-800 py-12"><div className="text-xs font-black uppercase tracking-[0.18em] text-violet-300">NFL Player Props{reviewMode ? " · Private review" : ""}</div><h1 className="mt-3 text-4xl font-black text-white">The NFL board is loading.</h1><p className="mt-4 max-w-2xl text-gray-400">The latest complete exact-price snapshot will appear after the NFL writer finishes its next validated cycle.</p></div></section>; }
function rank(row: Row): number { return ({ "Best Angle": 0, Lean: 1, Watchlist: 2, "No Play": 3, Held: 4 })[row.grade]; }
function key(row: Row): string { return [row.gameId, row.playerName, row.market, row.line, row.side].join("|"); }
function selection(row: Row): string { return row.side === "yes" ? "Anytime TD" : `${capitalize(row.side)} ${row.line}`; }
function focusBoard(): void { window.setTimeout(() => document.getElementById("nfl-props-board")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); }
function modelRead(row: Row): string {
  const priceCase = `OddSphere gives it a ${pct(row.finalProbability)} calibrated chance versus ${pct(row.marketProbability)} from the independent market, producing ${signedPct(row.expectedValue)} expected value at ${price(row.americanPrice)}.`;
  if (row.projection === null) return `This touchdown lane prices participation and scoring opportunity rather than raw hit rate. ${priceCase}`;
  const relation = row.projection >= row.line ? "above" : "below";
  return `The model projects ${row.projection.toFixed(1)}, ${Math.abs(row.projection - row.line).toFixed(1)} ${relation} the ${row.line} line. ${priceCase}`;
}
function label(value: string): string { return value.split("_").map(capitalize).join(" "); }
function capitalize(value: string): string { return value.charAt(0).toUpperCase() + value.slice(1); }
function pct(value: number): string { return `${(value * 100).toFixed(1)}%`; }
function signedPct(value: number): string { return `${value >= 0 ? "+" : ""}${(value * 100).toFixed(1)}%`; }
function price(value: number): string { return value > 0 ? `+${value}` : String(value); }
function impliedProbability(value: number): number { return value > 0 ? 100 / (value + 100) : Math.abs(value) / (Math.abs(value) + 100); }
function book(value: string): string { const labels: Record<string, string> = { draftkings: "DraftKings", fanduel: "FanDuel", novig: "NoVig", ballybet: "Bally Bet" }; return labels[value.toLowerCase()] ?? value; }
function localTime(value: string): string { return new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", timeZone: "America/New_York", timeZoneName: "short" }); }
