"use client";

import { useEffect, useMemo, useState } from "react";
import type { NflPlayerPropsMemberDecision as Row, NflPlayerPropsMemberGrade, NflPlayerPropsMemberSnapshot } from "@/lib/services/football/nflPlayerPropsProductionContract";
import type { NflPlayerPropsForecastTrend } from "@/lib/services/football/nflPlayerPropsRuntime";
import { PlayerPropReaderDialog } from "./PlayerPropReaderDialog";
import {
  PlayerPropsFilterButton,
  PlayerPropsRadarCardFrame,
  PlayerPropsSectionHeading,
  PlayerPropsSlateHero,
} from "./PlayerPropsProductUi";

type GradeFilter = "All" | NflPlayerPropsMemberGrade;
type SortKey = "signal" | "player" | "market" | "start" | "ev" | "edge" | "probability" | "book" | "updated";
type GameSummary = { gameId: string; teams: string[]; opponent: string | null; scheduledStart: string | null; rows: number };
type MarketPair = { key: string; rows: Row[]; primary: Row; over: Row | null; under: Row | null; yes: Row | null };

export function NflPlayerPropsProductDashboard({ snapshot, reviewMode = false, initialSelectedKey = null }: { snapshot: NflPlayerPropsMemberSnapshot | null; reviewMode?: boolean; initialSelectedKey?: string | null }) {
  const [selectedGame, setSelectedGame] = useState("all");
  const [grade, setGrade] = useState<GradeFilter>("All");
  const [market, setMarket] = useState("all");
  const [bookFilter, setBookFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState<SortKey>("signal");
  const [selectedKey, setSelectedKey] = useState<string | null>(initialSelectedKey);
  const allRows = useMemo(() => snapshot?.memberDecisions ?? [], [snapshot]);
  const games = useMemo(() => deriveGames(allRows), [allRows]);
  const markets = useMemo(() => unique(allRows.map((row) => row.market)).sort(), [allRows]);
  const books = useMemo(() => unique(allRows.map((row) => row.sportsbook)).sort(), [allRows]);
  const rows = useMemo(() => allRows.filter((row) => (
    (selectedGame === "all" || row.gameId === selectedGame)
    && (grade === "All" || row.grade === grade)
    && (market === "all" || row.market === market)
    && (bookFilter === "all" || row.sportsbook === bookFilter)
    && (!search.trim() || `${row.playerName} ${row.team} ${row.opponent} ${row.market} ${row.sportsbook}`.toLowerCase().includes(search.trim().toLowerCase()))
  )).sort(sortRows(sort)), [allRows, bookFilter, grade, market, search, selectedGame, sort]);
  const radarRows = useMemo(() => buildRadarRows(allRows), [allRows]);
  const pairs = useMemo(() => pairRows(rows), [rows]);
  const selected = allRows.find((row) => key(row) === selectedKey) ?? null;
  const activeFilters = [selectedGame, grade, market, bookFilter].filter((value) => value !== "all" && value !== "All").length + (search.trim() ? 1 : 0);

  useEffect(() => {
    const url = new URL(window.location.href);
    if (selectedKey) url.searchParams.set("reader", selectedKey);
    else url.searchParams.delete("reader");
    window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
  }, [selectedKey]);

  if (!snapshot) return <EmptyBoard reviewMode={reviewMode} />;

  const clearFilters = () => { setSelectedGame("all"); setGrade("All"); setMarket("all"); setBookFilter("all"); setSearch(""); };
  return <div className="w-full pb-8" data-review-surface={reviewMode ? "nfl-player-props" : undefined}>
    {reviewMode ? <aside className="mb-5 border border-amber-400/40 bg-amber-400/[0.08] px-4 py-3 sm:px-5"><p className="text-[10px] font-black uppercase text-amber-300">Private founder review · Real board</p><p className="mt-1 max-w-4xl text-sm leading-6 text-amber-50/80">This view uses the current timestamped NFL model output and exact prices. Review mode does not publish, grade, lock, or track anything.</p></aside> : null}
    <NflSlateHeader snapshot={snapshot} games={games} selectedGame={selectedGame} onSelectGame={setSelectedGame} reviewMode={reviewMode} />
    <TodayRadar rows={radarRows} onSelect={setSelectedKey} />

    <section data-product-zone="research-entry" className="z-30 -mx-4 border-y border-gray-800 bg-[#07090d]/95 px-4 py-4 shadow-[0_12px_30px_rgba(0,0,0,0.3)] backdrop-blur sm:sticky sm:top-16 sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
        <div className="shrink-0 lg:w-40"><p className="text-[10px] font-black uppercase text-violet-300">Research workspace</p><h2 className="mt-1 text-lg font-black text-white">Explore the board</h2></div>
        <label className="relative block min-w-0 flex-1"><span className="sr-only">Search NFL player props</span><span aria-hidden="true" className="pointer-events-none absolute inset-y-0 left-3 flex items-center text-sm text-gray-600">⌕</span><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search a player, team, market, or sportsbook" className="h-11 w-full rounded-md border border-gray-700 bg-gray-950 pl-9 pr-3 text-sm text-white outline-none placeholder:text-gray-600 focus:border-violet-400" /></label>
        <p className="shrink-0 text-xs text-gray-500"><strong className="text-gray-200">{pairs.length}</strong> markets shown · {allRows.length} completed reads</p>
      </div>
      <div className="mt-3 flex gap-2 overflow-x-auto pb-1" aria-label="NFL prop markets"><PlayerPropsFilterButton label="All markets" active={market === "all"} onClick={() => setMarket("all")} />{markets.map((value) => <PlayerPropsFilterButton key={value} label={label(value)} active={market === value} onClick={() => setMarket(value)} />)}</div>
      <div data-product-zone="board-controls" className="mt-3 border-t border-gray-800 pt-3"><div className="flex flex-wrap items-center gap-2">
        <FilterSelect label="Bet grade" value={grade} onChange={(value) => setGrade(value as GradeFilter)} options={["All", "Best Angle", "Lean", "Watchlist", "No Play"]} />
        <FilterSelect label="Sort" value={sort} onChange={(value) => setSort(value as SortKey)} options={[{ value: "signal", label: "Signal first" }, { value: "player", label: "Player A–Z" }, { value: "market", label: "Market" }, { value: "start", label: "Start time" }, { value: "ev", label: "Highest EV" }, { value: "edge", label: "Highest model edge" }, { value: "probability", label: "Model probability" }, { value: "book", label: "Book" }, { value: "updated", label: "Last updated" }]} />
        <FilterSelect label="Sportsbook" value={bookFilter} onChange={setBookFilter} options={["all", ...books]} />
        {activeFilters ? <button type="button" onClick={clearFilters} className="h-9 px-2 text-xs font-bold text-sky-300 hover:text-white">Clear {activeFilters}</button> : null}
      </div></div>
    </section>

    <FullBoard pairs={pairs} rows={rows} selectedKey={selectedKey} onSelect={setSelectedKey} />
    <details className="mt-6 rounded-lg border border-gray-800 bg-black/20 px-4 py-3 text-xs leading-5 text-gray-500"><summary className="cursor-pointer font-bold text-gray-300">Board coverage & availability</summary><div className="mt-2 grid gap-1 sm:grid-cols-2"><p><strong className="text-gray-300">{snapshot.board.diagnostics.inputOffers}</strong> raw offers received</p><p><strong className="text-gray-300">{snapshot.board.diagnostics.completedEvaluations}</strong> completed member evaluations</p><p><strong className="text-gray-300">{snapshot.board.diagnostics.completeExactOffers}</strong> complete exact offers evaluated</p><p><strong className="text-gray-300">{snapshot.board.diagnostics.incompleteExactOffers}</strong> incomplete line/price offers unavailable</p><p><strong className="text-gray-300">{snapshot.board.diagnostics.unavailableNoIndependentBenchmark}</strong> outcomes without an independent same-line benchmark</p><p><strong className="text-gray-300">{snapshot.board.diagnostics.unavailableStaleQuotes}</strong> stale outcomes unavailable</p><p><strong className="text-gray-300">{snapshot.board.diagnostics.unavailableFeatureContext}</strong> outcomes without complete model context</p><p><strong className="text-gray-300">{markets.length}</strong> market families currently graded</p></div><p className="mt-2">Completed member rows carry Best Angle, Lean, Watchlist, or No Play. Offers without a complete public evaluation are excluded from the board; they are not relabeled as No Play.</p></details>
    {selected ? <PropReader row={selected} onClose={() => setSelectedKey(null)} /> : null}
  </div>;
}

function NflSlateHeader({ snapshot, games, selectedGame, onSelectGame, reviewMode }: { snapshot: NflPlayerPropsMemberSnapshot; games: GameSummary[]; selectedGame: string; onSelectGame: (value: string) => void; reviewMode: boolean }) {
  return <header data-product-zone="slate-intelligence" className="border-b border-gray-800 pb-6"><PlayerPropsSlateHero
    badge={reviewMode ? <span className="mb-2 inline-flex rounded border border-amber-400/30 px-2 py-1 text-[10px] font-black uppercase text-amber-200">Review only</span> : null}
    eyebrow={<>NFL · Week {snapshot.week}</>}
    title="Player Props"
    description="Start with today’s strongest model reads, compare the best available price, then open the full OddSphere research before making a decision."
    status={<>Prices updated {localTime(snapshot.board.evaluatedAt)}</>}
    statusDetail={<>Exact offered prices across {unique(snapshot.memberDecisions.map((row) => row.sportsbook)).length} books · freezes at T-60</>}
    metrics={[
      { label: "Best angles", value: String(snapshot.board.counts["Best Angle"]), tone: "best" },
      { label: "Model leans", value: String(snapshot.board.counts.Lean), tone: "lean" },
      { label: "This week’s games", value: String(games.length), tone: "slate" },
    ]}
  />{games.length ? <GameNavigator games={games} rows={snapshot.memberDecisions} selectedGame={selectedGame} onSelectGame={onSelectGame} /> : null}</header>;
}

function GameNavigator({ games, rows, selectedGame, onSelectGame }: { games: GameSummary[]; rows: Row[]; selectedGame: string; onSelectGame: (value: string) => void }) {
  return <div className="mt-3"><div className="mb-2 flex items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase text-violet-300">Choose a matchup</p><p className="mt-0.5 text-[10px] text-gray-600">Select a game to filter every model read and market below.</p></div>{selectedGame !== "all" ? <button type="button" onClick={() => onSelectGame("all")} className="text-[10px] font-bold text-sky-300 hover:text-white">Show full slate</button> : null}</div><div className="flex gap-2 overflow-x-auto pb-1" aria-label="NFL slate games">
    <button type="button" onClick={() => onSelectGame("all")} aria-pressed={selectedGame === "all"} className={`group w-[190px] shrink-0 rounded-lg border px-4 py-3 text-left transition ${selectedGame === "all" ? "border-violet-400 bg-violet-400/[0.10]" : "border-gray-800 bg-[#0d1015] hover:-translate-y-0.5 hover:border-violet-400/50"}`}><span className="text-[10px] font-black uppercase text-violet-300">Full slate</span><strong className="mt-1 block text-base text-white">All {games.length} games</strong><span className="mt-3 block border-t border-white/[0.06] pt-2 text-[10px] font-black text-gray-400">{rows.length} completed reads →</span></button>
    {games.map((game) => <button type="button" key={game.gameId} onClick={() => onSelectGame(game.gameId)} aria-pressed={selectedGame === game.gameId} className={`group w-[250px] shrink-0 rounded-lg border px-4 py-3 text-left transition ${selectedGame === game.gameId ? "border-violet-400 bg-violet-400/[0.10]" : "border-gray-800 bg-[#0d1015] hover:-translate-y-0.5 hover:border-violet-400/50"}`}><span className="flex items-center justify-between gap-3"><span className="flex items-center gap-2">{game.teams.map((team) => <NflTeamBadge key={team} team={team} size="small" />)}</span><span className="text-[10px] text-gray-500">{gameTime(game.scheduledStart)}</span></span><strong className="mt-2 block truncate text-sm text-white">{gameLabel(game)}</strong><span className="mt-3 block border-t border-white/[0.06] pt-2 text-[10px] font-black text-gray-400">{game.rows} reads →</span></button>)}
  </div></div>;
}

function TodayRadar({ rows, onSelect }: { rows: Row[]; onSelect: (value: string) => void }) {
  return <section data-product-zone="today-radar" className="border-b border-gray-800 py-7"><PlayerPropsSectionHeading eyebrow="Today’s Radar" title="Model reads worth a look" count={`${rows.length} reads`} /><div className="mt-4 flex snap-x gap-3 overflow-x-auto pb-2" aria-label="Model reads worth a look">{rows.map((row, index) => <RadarCard key={key(row)} row={row} index={index} onSelect={onSelect} />)}</div></section>;
}

function RadarCard({ row, index, onSelect }: { row: Row; index: number; onSelect: (value: string) => void }) {
  const colors = gradeColors(row.grade);
  return <PlayerPropsRadarCardFrame borderColor={colors.border} background={`linear-gradient(180deg, ${colors.background}, rgba(14,18,24,0.98) 42%)`} accentColor={nflTeamColor(row.team)} watermark={<span className="text-[96px] font-black tracking-tighter text-white">{row.team}</span>}>
    <div className="flex items-start justify-between gap-3"><span className="text-[10px] font-black uppercase text-violet-300">{index === 0 && row.grade === "Best Angle" ? "Top rated" : row.grade === "Lean" ? "Model lean" : "Worth a look"}</span><GradeBadge grade={row.grade} /></div>
    <div className="mt-4 flex min-w-0 items-center gap-3"><NflTeamBadge team={row.team} /><div className="min-w-0"><h3 className="truncate text-base font-black text-white">{row.playerName}</h3><p className="truncate text-xs text-gray-500">{row.team} · {row.opponent} · {label(row.market)}</p></div></div>
    <div className="mt-5 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3"><div><p className="text-[9px] font-bold uppercase text-gray-600">Prediction</p><p className="mt-1 text-2xl font-black text-white">{selection(row)}</p></div><div className="text-right"><p className="text-[9px] font-bold uppercase text-gray-600">Best price</p><p className="mt-1 text-xl font-black text-white">{price(row.americanPrice)}</p><p className="text-[10px] text-gray-500">{book(row.sportsbook)}</p></div></div>
    <div className="mt-4 border-y border-gray-800 py-3"><div className="flex items-center justify-between text-xs"><span className="text-gray-500">Projection <strong className="ml-1 text-white">{projectionValue(row)}</strong></span><span className="text-gray-500">Edge <strong className={row.probabilityEdge > 0 ? "ml-1 text-emerald-300" : "ml-1 text-gray-300"}>{signedPct(row.probabilityEdge)}</strong></span></div><p className="mt-2 text-xs leading-5 text-gray-400">{shortModelRead(row)}</p></div>
    <button type="button" onClick={() => onSelect(key(row))} className="mt-4 h-9 w-full rounded-md border border-gray-700 text-xs font-black text-gray-100 hover:border-violet-400 hover:bg-violet-500/10">Open Reader</button>
  </PlayerPropsRadarCardFrame>;
}

function FullBoard({ pairs, rows, selectedKey, onSelect }: { pairs: MarketPair[]; rows: Row[]; selectedKey: string | null; onSelect: (value: string) => void }) {
  return <section id="nfl-props-board" data-product-zone="full-board" className="scroll-mt-24 pt-5"><div className="mb-3 flex items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase text-gray-500">Search results</p><h2 className="mt-1 text-xl font-black text-white">Prop Board</h2></div><p className="text-right text-xs text-gray-500"><strong className="text-gray-200">{pairs.length}</strong> markets shown<br />{rows.length} exact-price reads</p></div>{pairs.length ? <><div className="hidden xl:block"><PairTable pairs={pairs} selectedKey={selectedKey} onSelect={onSelect} /></div><div className="grid gap-3 xl:hidden">{pairs.map((pair) => <PairCard key={pair.key} pair={pair} selectedKey={selectedKey} onSelect={onSelect} />)}</div></> : <div className="rounded-lg border border-gray-800 p-8 text-center text-sm text-gray-500">No props match these controls.</div>}</section>;
}

function PairTable({ pairs, selectedKey, onSelect }: { pairs: MarketPair[]; selectedKey: string | null; onSelect: (value: string) => void }) {
  return <div className="overflow-hidden rounded-lg border border-gray-800 bg-gray-950"><div className="grid grid-cols-[1.35fr_0.9fr_1fr_1fr_0.8fr] gap-3 border-b border-gray-800 bg-[#151922] px-4 py-3 text-[9px] font-black uppercase tracking-wider text-gray-600"><span>Player / matchup</span><span>Market / forecast</span><span>Over / Yes</span><span>Under</span><span>Strongest grade</span></div><div className="divide-y divide-gray-800">{pairs.map((pair) => <div key={pair.key} className="grid grid-cols-[1.35fr_0.9fr_1fr_1fr_0.8fr] items-center gap-3 px-4 py-3"><span className="min-w-0"><strong className="block truncate text-sm text-white">{pair.primary.playerName}</strong><span className="mt-0.5 block truncate text-[10px] text-gray-500">{matchup(pair.primary)} · {gameTime(pair.primary.scheduledStart)}</span></span><span><strong className="block text-xs text-white">{label(pair.primary.market)} {pair.primary.line}</strong><span className="mt-0.5 block text-[10px] text-gray-500">Projection {projectionValue(pair.primary)}</span></span><SideQuote row={pair.over ?? pair.yes} selectedKey={selectedKey} onSelect={onSelect} /><SideQuote row={pair.under} selectedKey={selectedKey} onSelect={onSelect} /><GradeBadge grade={pair.primary.grade} /></div>)}</div></div>;
}

function PairCard({ pair, selectedKey, onSelect }: { pair: MarketPair; selectedKey: string | null; onSelect: (value: string) => void }) {
  return <article className="rounded-lg border border-gray-800 bg-[#0e1218] p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><NflTeamBadge team={pair.primary.team} size="small" /><div className="min-w-0"><strong className="block truncate text-sm text-white">{pair.primary.playerName}</strong><span className="mt-0.5 block truncate text-xs text-gray-500">{matchup(pair.primary)} · {gameTime(pair.primary.scheduledStart)}</span></div></div><GradeBadge grade={pair.primary.grade} /></div><div className="mt-4 flex items-end justify-between border-y border-gray-800 py-3"><span><span className="block text-[9px] font-bold uppercase text-gray-600">{label(pair.primary.market)}</span><strong className="mt-1 block text-lg text-white">Line {pair.primary.line}</strong></span><span className="text-right"><span className="block text-[9px] font-bold uppercase text-gray-600">Projection</span><strong className="mt-1 block text-lg text-white">{projectionValue(pair.primary)}</strong></span></div><div className={`mt-3 grid gap-2 ${(pair.over ?? pair.yes) && pair.under ? "grid-cols-2" : "grid-cols-1"}`}><SideQuote row={pair.over ?? pair.yes} selectedKey={selectedKey} onSelect={onSelect} card /><SideQuote row={pair.under} selectedKey={selectedKey} onSelect={onSelect} card /></div></article>;
}

function SideQuote({ row, selectedKey, onSelect, card = false }: { row: Row | null; selectedKey: string | null; onSelect: (value: string) => void; card?: boolean }) {
  if (!row) return card ? null : <span className="text-xs text-gray-700">Not posted</span>;
  return <button type="button" onClick={() => onSelect(key(row))} aria-pressed={selectedKey === key(row)} className={`min-w-0 rounded-md border p-2.5 text-left transition ${selectedKey === key(row) ? "border-violet-400 bg-violet-400/10" : "border-gray-800 bg-black/20 hover:border-gray-700"}`}><span className="flex items-start justify-between gap-2"><strong className="text-xs text-white">{row.side === "yes" ? "Anytime TD" : capitalize(row.side)}</strong><span className="text-xs font-black text-emerald-300">{price(row.americanPrice)}</span></span><span className="mt-1 flex items-end justify-between gap-2 text-[9px] text-gray-600"><span>{book(row.sportsbook)}</span><span>{pct(row.finalProbability)} · {signedPct(row.expectedValue)} EV</span></span></button>;
}

function PropReader({ row, onClose }: { row: Row; onClose: () => void }) {
  const comparisons = [...(row.bookEvidence ?? [{ sportsbook: row.sportsbook, provider: row.provider, americanPrice: row.americanPrice, observedAt: row.observedAt, openingObservedAt: null, openingAmericanPrice: null }])].sort((a, b) => b.americanPrice - a.americanPrice);
  const selectedBook = comparisons.find((value) => normalizeBook(value.sportsbook) === normalizeBook(row.sportsbook) && value.provider === row.provider) ?? null;
  const hasMovement = Boolean(selectedBook?.openingObservedAt && selectedBook.openingAmericanPrice !== null);
  return <PlayerPropReaderDialog ariaLabel={`${row.playerName} prop details`} title={row.playerName} leading={<NflTeamBadge team={row.team} size="small" />} onClose={onClose}><div className="grid min-w-0 gap-4 p-4 sm:p-6 lg:grid-cols-2">
    <div className="min-w-0 lg:col-span-2"><ReaderPanel title="Prop Summary"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm text-gray-500">{matchup(row)} · {label(row.market)} · starts {fullGameTime(row.scheduledStart)}</span>{row.state === "locked" ? <LockBadge lockedAt={row.lockAt} /> : null}</div><p className="mt-3 text-3xl font-black text-white">{selection(row)} <span className="text-emerald-300">{price(row.americanPrice)}</span></p><p className="mt-1 text-xs text-gray-500">{book(row.sportsbook)} · {provider(row.provider)} · price observed {localTime(row.observedAt)}</p></div><GradeBadge grade={row.grade} /></div></ReaderPanel></div>
    <div className="min-w-0 lg:col-span-2"><ReaderPanel title="Reader Summary"><p className="max-w-3xl text-base font-semibold leading-7 text-gray-100">{modelRead(row)}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t border-gray-800 pt-3 text-xs"><span className="text-gray-500">Bet grade <strong className="ml-1 text-gray-200">{row.grade}</strong></span><span className="text-gray-500">Role confidence <strong className="ml-1 text-gray-200">{pct(row.participationProbability)}</strong></span><span className="text-gray-500">Updated <strong className="ml-1 text-gray-200">{localTime(row.observedAt)}</strong></span><span className="text-gray-500">{row.state === "locked" ? "Locked" : "Locks"} <strong className="ml-1 text-gray-200">{localTime(row.lockAt)}</strong></span></div></ReaderPanel></div>
    <div className="min-w-0 lg:col-span-2"><ReaderPanel title="OddSphere Forecast"><ProjectionVisual row={row} /></ReaderPanel></div>
    <ReaderPanel title="Model Comparison"><ProbabilityVisual row={row} /><div className="mt-3 grid grid-cols-3 gap-2"><Metric title="Model edge" value={signedPct(row.probabilityEdge)} positive={row.probabilityEdge > 0} /><Metric title="Expected value" value={signedPct(row.expectedValue)} positive={row.expectedValue > 0} /><Metric title="Model chance" value={pct(row.finalProbability)} /></div></ReaderPanel>
    <ReaderPanel title="Projection Context"><ForecastContext row={row} /></ReaderPanel>
    <ReaderPanel title="Available Exact Prices"><div className="overflow-hidden rounded-lg border border-gray-800">{comparisons.map((value, index) => <div key={`${value.provider}|${normalizeBook(value.sportsbook)}`} className={`flex items-center justify-between gap-3 border-b border-gray-800 px-3 py-3 last:border-b-0 ${index === 0 ? "bg-emerald-400/5" : ""}`}><span><strong className="block text-xs text-white">{book(value.sportsbook)}</strong><span className="text-[9px] text-gray-600">{provider(value.provider)} · {localTime(value.observedAt)}</span>{index === 0 ? <span className="mt-0.5 block text-[9px] font-black uppercase text-emerald-300">Best price</span> : null}</span><span className="text-right"><strong className="block text-white">{price(value.americanPrice)}</strong><span className="text-[9px] text-gray-600">{pct(impliedProbability(value.americanPrice))} implied</span></span></div>)}</div></ReaderPanel>
    <ReaderPanel title="Same-Book Movement">{hasMovement && selectedBook ? <div className="rounded-lg border border-gray-800 bg-black/20 p-4"><div className="grid grid-cols-2 gap-3"><span><span className="block text-[9px] font-black uppercase tracking-wider text-gray-600">Opening</span><strong className="mt-1 block text-lg text-white">{price(selectedBook.openingAmericanPrice!)}</strong><span className="block text-[10px] text-gray-500">{localTime(selectedBook.openingObservedAt!)}</span></span><span className="text-right"><span className="block text-[9px] font-black uppercase tracking-wider text-gray-600">Current</span><strong className="mt-1 block text-lg text-white">{price(selectedBook.americanPrice)}</strong><span className="block text-[10px] text-gray-500">{localTime(selectedBook.observedAt)}</span></span></div><p className="mt-3 border-t border-gray-800 pt-3 text-[10px] text-gray-500">Same sportsbook and exact {selection(row).toLowerCase()} outcome · {book(selectedBook.sportsbook)} · {provider(selectedBook.provider)}</p></div> : <UnavailableEvidence title="Opening movement is not available yet" detail="OddSphere will show a same-sportsbook opening-to-current trail only after a genuine earlier quote is retained. No movement is fabricated." />}</ReaderPanel>
    <ReaderPanel title="Role & Matchup Context"><ForecastContextDetails row={row} /></ReaderPanel>
    <ReaderPanel title="What Could Change"><p className="text-sm leading-6 text-gray-200">A material price, role, roster, quarterback, injury, or opponent-context update triggers a fresh forecast and exact-price decision while this prop is unlocked. At T-60, the model, line, side, sportsbook price, and grade freeze for official tracking.</p></ReaderPanel>
    <ReaderPanel title="Decision Status"><div className="rounded-lg border border-violet-400/20 bg-violet-400/[0.05] p-4 text-xs leading-5 text-gray-400"><strong className="text-violet-200">Exact-price decision:</strong> {pct(row.finalProbability)} calibrated probability at {price(row.americanPrice)} produces {signedPct(row.expectedValue)} expected value. The independent market is comparison evidence, not a copied forecast.</div></ReaderPanel>
    <p className="min-w-0 break-words text-[10px] leading-5 text-gray-600 lg:col-span-2">Model {row.modelRelease} · calibration {row.calibrationRelease} · decision {row.decisionRelease} · {row.state === "locked" ? "frozen at T-60" : `locks ${localTime(row.lockAt)}`}</p>
  </div></PlayerPropReaderDialog>;
}

function ProjectionVisual({ row }: { row: Row }) {
  if (row.projection === null) return <div className="rounded-lg border border-gray-800 bg-black/20 p-4 text-sm leading-6 text-gray-300">OddSphere forecasts a <strong className="text-white">{pct(row.rawModelProbability)}</strong> anytime-touchdown chance from participation, role opportunity, team scoring environment, and opponent context. The exact offered price is evaluated separately.</div>;
  const range = row.projectionRange; const high = Math.max(row.projection, row.line, range?.upper ?? 0) * 1.15 || 1; const position = (value: number) => `${Math.max(4, Math.min(96, value / high * 100))}%`;
  return <div className="rounded-lg border border-gray-800 bg-black/20 p-4"><div className="flex justify-between gap-2 text-xs"><span className="text-gray-500">Projection <strong className="text-white">{row.projection.toFixed(1)}</strong></span><span className="font-bold text-sky-300">Favors {row.projection > row.line ? "Over" : "Under"}</span><span className="text-gray-500">Line <strong className="text-white">{row.line}</strong></span></div><div className="relative mt-6 h-2 rounded-full bg-gray-800">{range ? <span className="absolute -top-0.5 h-3 rounded-full bg-violet-400/30" style={{ left: position(range.lower), width: `calc(${position(range.upper)} - ${position(range.lower)})` }} /> : null}<span className="absolute -top-1.5 h-5 w-0.5 bg-white" style={{ left: position(row.line) }} /><span className="absolute -top-1 h-4 w-4 -translate-x-1/2 rounded-full border-2 border-gray-950 bg-sky-400" style={{ left: position(row.projection) }} /></div>{range ? <p className="mt-4 text-xs leading-5 text-gray-500">Empirical 80% model range <strong className="text-gray-200">{range.lower.toFixed(1)}–{range.upper.toFixed(1)}</strong>. This describes forecast uncertainty, not a guarantee.</p> : null}</div>;
}

function ForecastContext({ row }: { row: Row }) {
  const context = row.forecastContext;
  if (!context) return <UnavailableEvidence title="Projection context is updating" detail="The forecast and exact-price decision remain visible; verified role and matchup context will populate on the next scheduled refresh." />;
  const metrics = [context.recentProduction, ...context.roleOpportunity, context.opponentAllowance].filter((value): value is NonNullable<typeof value> => value !== null);
  const trends = context.modelInputTrends ?? [];
  return <div className="space-y-3"><div className="overflow-hidden rounded-lg border border-gray-800 bg-black/20"><div className="grid grid-cols-2 gap-px bg-gray-800 sm:grid-cols-3">{metrics.map((metric) => <div key={metric.label} className="bg-gray-950 p-3"><p className="text-[9px] font-bold uppercase leading-4 text-gray-600">{metric.label}</p><p className="mt-1 text-base font-black text-gray-100">{forecastMetric(metric)}</p></div>)}</div><p className="border-t border-gray-800 p-4 text-[10px] leading-5 text-gray-600">Inputs captured {localTime(context.featureAsOf)}. These inputs explain the forecast; the sportsbook price is evaluated separately.</p></div>{trends.length ? <div className="space-y-3">{trends.map((trend) => <ModelInputTrend key={trend.label} trend={trend} />)}<p className="text-[10px] leading-5 text-gray-600"><strong className="text-violet-200">Actual model inputs.</strong> Last game, L3, L5, and model-weighted values come from the timestamped feature row used to create this projection. Dated game logs and player-vs-opponent history are not in the current production payload, so OddSphere does not invent them.</p></div> : <UnavailableEvidence title="Detailed trend windows are not in this stored snapshot" detail="This older snapshot retains the valid projection and aggregate context. Last game, L3, L5, and model-weighted inputs will appear after the next normal writer refresh." />}</div>;
}

function ModelInputTrend({ trend }: { trend: NflPlayerPropsForecastTrend }) {
  const labels = { last_game: "Last game", last_3_average: "L3 avg", last_5_average: "L5 avg", model_weighted: "Model-weighted" } as const;
  return <section className="overflow-hidden rounded-lg border border-gray-800 bg-black/20"><div className="flex items-center justify-between gap-3 border-b border-gray-800 px-4 py-3"><h3 className="text-xs font-black text-gray-200">{trend.label}</h3><span className="rounded border border-violet-400/25 bg-violet-400/[0.06] px-2 py-1 text-[8px] font-black uppercase tracking-wider text-violet-200">Model input</span></div><div className="grid grid-cols-2 gap-px bg-gray-800 sm:grid-cols-4">{trend.points.map((point) => <div key={point.window} className="bg-gray-950 px-3 py-3"><span className="block text-[8px] font-black uppercase tracking-wider text-gray-600">{labels[point.window]}</span><strong className="mt-1 block text-base text-white">{trendValue(point.value, trend.format)}</strong></div>)}</div></section>;
}

function ForecastContextDetails({ row }: { row: Row }) {
  const context = row.forecastContext;
  if (!context) return <UnavailableEvidence title="Verified context is updating" detail="OddSphere keeps this field unavailable rather than inventing role, quarterback, injury, or team context." />;
  return <div className="space-y-3 rounded-lg border border-gray-800 bg-black/20 p-4 text-xs leading-5 text-gray-400"><p><strong className="text-gray-200">Role confidence:</strong> {pct(row.participationProbability)}</p><p><strong className="text-gray-200">Team environment:</strong> {context.teamImpliedPoints === null ? "verified team total unavailable" : `${context.teamImpliedPoints.toFixed(1)} implied points`}.</p><p><strong className="text-gray-200">Quarterback:</strong> {context.expectedQuarterback ? `${context.expectedQuarterback.name} · ${context.expectedQuarterback.starterStatus}` : "expected quarterback unavailable"}.</p><p><strong className="text-gray-200">Availability:</strong> {availabilityText(context.availability)}</p></div>;
}

function ProbabilityVisual({ row }: { row: Row }) { return <div className="rounded-lg border border-gray-800 bg-black/20 p-4"><ProbabilityBar title="OddSphere calibrated" value={row.finalProbability} tone="bg-violet-400" /><div className="mt-4"><ProbabilityBar title="Independent market" value={row.marketProbability} tone="bg-sky-400" /></div><div className="mt-4 flex justify-between border-t border-gray-800 pt-3 text-xs"><span className="text-gray-500">Probability edge</span><strong className={row.probabilityEdge > 0 ? "text-emerald-300" : "text-gray-300"}>{signedPct(row.probabilityEdge)}</strong></div></div>; }
function ProbabilityBar({ title, value, tone }: { title: string; value: number; tone: string }) { return <div><div className="flex justify-between text-xs"><span className="text-gray-400">{title}</span><strong className="text-white">{pct(value)}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-gray-800"><span className={`block h-full rounded-full ${tone}`} style={{ width: `${value * 100}%` }} /></div></div>; }
function ReaderPanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="min-w-0"><p className="mb-3 text-[10px] font-black uppercase tracking-wider text-gray-500">{title}</p>{children}</section>; }
function UnavailableEvidence({ title, detail }: { title: string; detail: string }) { return <div className="rounded-lg border border-dashed border-gray-700 bg-black/20 p-4"><p className="text-sm font-bold text-gray-300">{title}</p><p className="mt-1 text-xs leading-5 text-gray-500">{detail}</p></div>; }
function LockBadge({ lockedAt }: { lockedAt: string }) { return <span className="inline-flex rounded border border-sky-400/30 bg-sky-400/10 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-sky-200">Locked T-60 · {localTime(lockedAt)}</span>; }
function GradeBadge({ grade }: { grade: Row["grade"] }) { const colors = gradeColors(grade); return <span className="inline-flex w-fit rounded border px-2 py-1 text-[9px] font-black uppercase tracking-wider" style={{ borderColor: colors.border, background: colors.background, color: colors.text }}>{grade}</span>; }
function Metric({ title, value, positive = false }: { title: string; value: string; positive?: boolean }) { return <span className="text-center"><span className="block text-[8px] font-bold uppercase text-gray-600">{title}</span><strong className={`mt-1 block text-xs ${positive ? "text-emerald-300" : "text-gray-200"}`}>{value}</strong></span>; }
function FilterSelect({ label: title, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: ReadonlyArray<string | { value: string; label: string }> }) { return <label className="flex h-9 items-center gap-2 rounded-md border border-gray-700 bg-gray-950 px-3"><span className="text-[9px] font-black uppercase text-gray-600">{title}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="min-w-0 bg-transparent text-xs font-bold text-gray-200 outline-none">{options.map((option) => { const item = typeof option === "string" ? { value: option, label: option === "all" ? "All" : option } : option; return <option key={item.value} value={item.value}>{item.label}</option>; })}</select></label>; }
function NflTeamBadge({ team, size = "normal" }: { team: string; size?: "small" | "normal" }) { const dimension = size === "small" ? "h-7 w-7 text-[8px]" : "h-10 w-10 text-[10px]"; return <span aria-label={team} className={`inline-flex shrink-0 items-center justify-center rounded-full font-black text-white ring-1 ring-white/15 ${dimension}`} style={{ backgroundColor: nflTeamColor(team) }}>{team}</span>; }
function EmptyBoard({ reviewMode }: { reviewMode: boolean }) { return <section className="mx-auto max-w-4xl py-10 sm:py-20"><div className="border-y border-gray-800 py-10 sm:py-14"><div className="flex items-center gap-3 text-xs font-bold text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400" />NFL Player Props{reviewMode ? " · Private review" : ""}</div><h1 className="mt-5 max-w-2xl text-4xl font-black leading-tight text-white sm:text-5xl">Today’s prop board is loading.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-gray-400">The latest complete exact-price snapshot will appear here as soon as sportsbook prices are ready.</p></div></section>; }

function pairRows(rows: Row[]): MarketPair[] { const groups = new Map<string, Row[]>(); for (const row of rows) { const pairKey = [row.gameId, row.playerName, row.market, row.line].join("|"); groups.set(pairKey, [...(groups.get(pairKey) ?? []), row]); } return [...groups.entries()].map(([pairKey, pairRows]) => ({ key: pairKey, rows: pairRows, primary: [...pairRows].sort((a, b) => rank(a) - rank(b) || b.expectedValue - a.expectedValue)[0]!, over: pairRows.find((row) => row.side === "over") ?? null, under: pairRows.find((row) => row.side === "under") ?? null, yes: pairRows.find((row) => row.side === "yes") ?? null })).sort((a, b) => sortRows("signal")(a.primary, b.primary)); }
function deriveGames(rows: Row[]): GameSummary[] { const map = new Map<string, GameSummary>(); for (const row of rows) { const game = map.get(row.gameId) ?? { gameId: row.gameId, teams: [], opponent: row.opponent || null, scheduledStart: row.scheduledStart || null, rows: 0 }; game.teams = unique([...game.teams, row.team]); if (row.opponent && !game.teams.includes(row.opponent) && game.teams.length < 2) game.teams.push(row.opponent); game.rows += 1; map.set(row.gameId, game); } return [...map.values()].sort((a, b) => Date.parse(a.scheduledStart ?? "") - Date.parse(b.scheduledStart ?? "")); }
function buildRadarRows(rows: Row[]): Row[] { const deduped = new Map<string, Row>(); for (const row of [...rows].sort(sortRows("signal"))) { const radarKey = [row.gameId, row.playerName, row.market].join("|"); if (!deduped.has(radarKey)) deduped.set(radarKey, row); } return [...deduped.values()].filter((row) => row.grade !== "No Play").slice(0, 6); }
function sortRows(sort: SortKey): (a: Row, b: Row) => number { if (sort === "player") return (a, b) => a.playerName.localeCompare(b.playerName); if (sort === "market") return (a, b) => a.market.localeCompare(b.market) || a.playerName.localeCompare(b.playerName); if (sort === "start") return (a, b) => Date.parse(a.scheduledStart) - Date.parse(b.scheduledStart); if (sort === "ev") return (a, b) => b.expectedValue - a.expectedValue; if (sort === "edge") return (a, b) => b.probabilityEdge - a.probabilityEdge; if (sort === "probability") return (a, b) => b.finalProbability - a.finalProbability; if (sort === "book") return (a, b) => a.sportsbook.localeCompare(b.sportsbook); if (sort === "updated") return (a, b) => Date.parse(b.observedAt) - Date.parse(a.observedAt); return (a, b) => rank(a) - rank(b) || b.expectedValue - a.expectedValue; }
function rank(row: Row): number { return ({ "Best Angle": 0, Lean: 1, Watchlist: 2, "No Play": 3 })[row.grade]; }
function key(row: Row): string { return [row.gameId, row.playerName, row.market, row.line, row.side].join("|"); }
function selection(row: Row): string { return row.side === "yes" ? "Anytime TD" : `${capitalize(row.side)} ${row.line}`; }
function projectionValue(row: Row): string { return row.projection === null ? `${pct(row.rawModelProbability)} TD` : row.projection.toFixed(1); }
function matchup(row: Row): string { return row.opponent ? `${row.team} · ${row.opponent}` : row.team; }
function gameLabel(game: GameSummary): string { return game.teams.length > 1 ? `${game.teams[0]} · ${game.teams[1]}` : game.opponent ? `${game.teams[0] ?? "NFL"} · ${game.opponent}` : game.teams[0] ?? "NFL matchup"; }
function shortModelRead(row: Row): string { if (row.projection === null) return `${pct(row.rawModelProbability)} touchdown forecast from role, team, and opponent context.`; return `${row.projection.toFixed(1)} projected against ${row.line}, with an empirical range retained in the reader.`; }
function modelRead(row: Row): string { const priceCase = `OddSphere gives it a ${pct(row.finalProbability)} calibrated chance versus ${pct(row.marketProbability)} from the independent market, producing ${signedPct(row.expectedValue)} expected value at ${price(row.americanPrice)}.`; if (row.projection === null) return `The model forecasts a ${pct(row.rawModelProbability)} touchdown probability from participation, role opportunity, team environment, and opponent context. ${priceCase}`; const relation = row.projection >= row.line ? "above" : "below"; const range = row.projectionRange ? ` Its empirical 80% range is ${row.projectionRange.lower.toFixed(1)}–${row.projectionRange.upper.toFixed(1)}.` : ""; return `The model projects ${row.projection.toFixed(1)}, ${Math.abs(row.projection - row.line).toFixed(1)} ${relation} the ${row.line} line.${range} ${priceCase}`; }
function gradeColors(grade: Row["grade"]): { border: string; background: string; text: string } { if (grade === "Best Angle") return { border: "#34d39966", background: "rgba(52,211,153,0.10)", text: "#6ee7b7" }; if (grade === "Lean") return { border: "#38bdf866", background: "rgba(56,189,248,0.10)", text: "#7dd3fc" }; if (grade === "Watchlist") return { border: "#fbbf2466", background: "rgba(251,191,36,0.10)", text: "#fcd34d" }; return { border: "#374151", background: "rgba(17,24,39,0.9)", text: "#9ca3af" }; }
function nflTeamColor(team: string): string { return NFL_TEAM_COLORS[team] ?? "#4B5563"; }
const NFL_TEAM_COLORS: Record<string, string> = { ARI: "#97233F", ATL: "#A71930", BAL: "#241773", BUF: "#00338D", CAR: "#0085CA", CHI: "#0B162A", CIN: "#FB4F14", CLE: "#311D00", DAL: "#003594", DEN: "#FB4F14", DET: "#0076B6", GB: "#203731", HOU: "#03202F", IND: "#002C5F", JAX: "#006778", KC: "#E31837", LV: "#000000", LAC: "#0080C6", LAR: "#003594", MIA: "#008E97", MIN: "#4F2683", NE: "#002244", NO: "#D3BC8D", NYG: "#0B2265", NYJ: "#125740", PHI: "#004C54", PIT: "#FFB612", SEA: "#002244", SF: "#AA0000", TB: "#D50A0A", TEN: "#0C2340", WSH: "#5A1414" };
function forecastMetric(metric: NonNullable<Row["forecastContext"]>["roleOpportunity"][number]): string { if (metric.format === "percent") return pct(metric.value); return metric.format === "yards" ? `${metric.value.toFixed(1)} yd` : metric.value.toFixed(1); }
function trendValue(value: number, format: "count" | "yards" | "percent"): string { if (format === "percent") return pct(value); return format === "yards" ? `${value.toFixed(1)} yd` : value.toFixed(1); }
function availabilityText(value: NonNullable<Row["forecastContext"]>["availability"]): string { const report = value.reportedAt ?? value.reportUpdatedAt; if (value.listed) return `${value.status ?? "listed"}${value.detail ? ` · ${value.detail}` : ""}${report ? ` · ${localTime(report)}` : ""}`; return `no matching active player listing in the ${value.source} report${report ? ` as of ${localTime(report)}` : ""}`; }
function unique(values: string[]): string[] { return [...new Set(values.filter(Boolean))]; }
function label(value: string): string { return value.split("_").map(capitalize).join(" "); }
function capitalize(value: string): string { return value.charAt(0).toUpperCase() + value.slice(1); }
function pct(value: number): string { return `${(value * 100).toFixed(1)}%`; }
function signedPct(value: number): string { return `${value >= 0 ? "+" : ""}${(value * 100).toFixed(1)}%`; }
function price(value: number): string { return value > 0 ? `+${value}` : String(value); }
function impliedProbability(value: number): number { return value > 0 ? 100 / (value + 100) : Math.abs(value) / (Math.abs(value) + 100); }
function normalizeBook(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]/g, ""); }
function book(value: string): string { const labels: Record<string, string> = { draftkings: "DraftKings", fanduel: "FanDuel", novig: "NoVig", ballybet: "Bally Bet" }; return labels[value.toLowerCase()] ?? value; }
function provider(value: string): string { return value === "balldontlie" ? "Ball Don’t Lie" : value === "sharpapi" ? "Sharp API" : value; }
function gameTime(value: string | null | undefined): string { const date = value ? new Date(value) : null; return date && Number.isFinite(date.getTime()) ? date.toLocaleString("en-US", { weekday: "short", hour: "numeric", minute: "2-digit", timeZone: "America/New_York" }) : "Start time pending"; }
function fullGameTime(value: string | null | undefined): string { const date = value ? new Date(value) : null; return date && Number.isFinite(date.getTime()) ? localTime(value!) : "unavailable"; }
function localTime(value: string): string { return new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", timeZone: "America/New_York", timeZoneName: "short" }); }
