/**
 * Read-only chronological audit of the MLB totals regime calibration.
 *
 * Input is the JSON generated by audit-daily-edge-loss-market-evidence.ts
 * with its enhanced total pre-champion probability evidence. No outcomes are
 * fetched or written here; the selected 90-game / 35% candidate is fixed in
 * lib/automodel/mlbTotalsRegimeCalibration.ts.
 */

import { readFileSync } from "node:fs";

type Row = {
  id: number;
  date: string;
  market: string;
  pick: string | null;
  side: string | null;
  price: number | null;
  result: string | null;
  modelProbability: number | null;
  totalPriceState: {
    preChampionSelectedSide: string | null;
    preChampionSelectedProbability: number | null;
    overPrice: number | null;
    underPrice: number | null;
  } | null;
};

type Observation = {
  id: number;
  date: string;
  baseOverProbability: number;
  productionOverProbability: number;
  productionPickOver: boolean;
  productionPrice: number | null;
  overPrice: number | null;
  underPrice: number | null;
  overWon: boolean;
};

type Evaluated = Observation & {
  candidateOverProbability: number;
  partition: "train" | "calibration" | "holdout";
};

function inputPath(argv: string[]): string {
  const arg = argv.find((value) => value.startsWith("--input="));
  if (arg) return arg.slice("--input=".length);
  const index = argv.indexOf("--input");
  if (index >= 0 && argv[index + 1]) return argv[index + 1]!;
  throw new Error("Usage: audit-mlb-totals-regime-calibration.ts --input report.json");
}

function partition(date: string): Evaluated["partition"] {
  if (date <= "2026-07-31") return "train";
  if (date <= "2026-08-31") return "calibration";
  return "holdout";
}

function clamp(value: number): number {
  return Math.max(0.01, Math.min(0.99, value));
}

function metrics(rows: Evaluated[], candidate: boolean): Record<string, number | null> {
  if (rows.length === 0) return {
    n: 0,
    accuracy: null,
    brier: null,
    logLoss: null,
    calibrationGapPp: null,
    priceRows: 0,
    units: null,
    roiPct: null,
  };
  let correct = 0;
  let brier = 0;
  let logLoss = 0;
  let probabilitySum = 0;
  let outcomeSum = 0;
  let priceRows = 0;
  let units = 0;
  for (const row of rows) {
    const probability = candidate
      ? row.candidateOverProbability
      : row.productionOverProbability;
    const outcome = row.overWon ? 1 : 0;
    const pickedOver = candidate ? probability >= 0.5 : row.productionPickOver;
    const won = pickedOver === row.overWon;
    if (won) correct++;
    const price = candidate
      ? pickedOver ? row.overPrice : row.underPrice
      : row.productionPrice;
    if (price !== null && Number.isFinite(price) && price !== 0) {
      priceRows++;
      units += won ? price > 0 ? price / 100 : 100 / Math.abs(price) : -1;
    }
    brier += (probability - outcome) ** 2;
    const bounded = clamp(probability);
    logLoss += -(outcome * Math.log(bounded) + (1 - outcome) * Math.log(1 - bounded));
    probabilitySum += probability;
    outcomeSum += outcome;
  }
  return {
    n: rows.length,
    accuracy: Number((correct / rows.length).toFixed(6)),
    brier: Number((brier / rows.length).toFixed(6)),
    logLoss: Number((logLoss / rows.length).toFixed(6)),
    calibrationGapPp: Number(((probabilitySum - outcomeSum) / rows.length * 100).toFixed(3)),
    priceRows,
    units: Number(units.toFixed(3)),
    roiPct: priceRows > 0 ? Number((units / priceRows * 100).toFixed(3)) : null,
  };
}

function evaluate(observations: Observation[], sampleSize: number, weight: number): Evaluated[] {
  const byDate = new Map<string, Observation[]>();
  for (const observation of observations) {
    const rows = byDate.get(observation.date) ?? [];
    rows.push(observation);
    byDate.set(observation.date, rows);
  }
  const history: Observation[] = [];
  const evaluated: Evaluated[] = [];
  for (const date of [...byDate.keys()].sort()) {
    const rows = byDate.get(date)!;
    if (history.length >= sampleSize) {
      const priorRows = history.slice(-sampleSize);
      const overWins = priorRows.filter((row) => row.overWon).length;
      const smoothedOverRate = (overWins + 5) / (sampleSize + 10);
      for (const row of rows) {
        evaluated.push({
          ...row,
          candidateOverProbability:
            (1 - weight) * row.baseOverProbability + weight * smoothedOverRate,
          partition: partition(row.date),
        });
      }
    }
    history.push(...rows.sort((a, b) => a.id - b.id));
  }
  return evaluated;
}

function main(): void {
  const report = JSON.parse(readFileSync(inputPath(process.argv), "utf8")) as { rows?: Row[] };
  const observations: Observation[] = (report.rows ?? []).flatMap((row) => {
    if (row.market !== "total" || (row.result !== "win" && row.result !== "loss")) return [];
    if (row.side !== "over" && row.side !== "under") return [];
    if (typeof row.modelProbability !== "number" || !Number.isFinite(row.modelProbability)) return [];
    const selectedSide = row.totalPriceState?.preChampionSelectedSide;
    if (selectedSide !== "over" && selectedSide !== "under") return [];
    const selected = row.totalPriceState?.preChampionSelectedProbability;
    if (typeof selected !== "number" || !Number.isFinite(selected)) return [];
    return [{
      id: row.id,
      date: row.date,
      baseOverProbability: selectedSide === "over" ? selected : 1 - selected,
      productionOverProbability:
        row.side === "over" ? row.modelProbability : 1 - row.modelProbability,
      productionPickOver: row.side === "over",
      productionPrice: row.price,
      overPrice: row.totalPriceState?.overPrice ?? null,
      underPrice: row.totalPriceState?.underPrice ?? null,
      overWon:
        (row.side === "over" && row.result === "win") ||
        (row.side === "under" && row.result === "loss"),
    }];
  });
  const selectionGrid = [60, 90, 120].flatMap((sampleSize) =>
    [0.2, 0.25, 0.3, 0.35, 0.4].map((weight) => {
      const evaluated = evaluate(observations, sampleSize, weight);
      const trainCalibration = evaluated.filter((row) => row.partition !== "holdout");
      return {
        sampleSize,
        weight,
        trainCalibrationCandidate: metrics(trainCalibration, true),
        trainCalibrationBaseline: metrics(trainCalibration, false),
      };
    }),
  );
  const selected = evaluate(observations, 90, 0.35);
  console.log(JSON.stringify({
    contract: "mlb_totals_regime_calibration_audit_2026_09_19_r1",
    rows: observations.length,
    selectionRule:
      "Choose the smallest tested weight/window that improves both train+calibration side accuracy and Brier; inspect holdout only after 90/0.35 is fixed.",
    selectionGrid,
    selectedCandidate: {
      sampleSize: 90,
      weight: 0.35,
      partitions: Object.fromEntries(
        (["train", "calibration", "holdout"] as const).map((name) => {
          const rows = selected.filter((row) => row.partition === name);
          return [name, {
            baseline: metrics(rows, false),
            candidate: metrics(rows, true),
          }];
        }),
      ),
    },
  }, null, 2));
}

main();
